// --------------------------------------------------------------------------------------------------------------------
// <copyright file="hb_title_set_s.cs" company="HandBrake Project (http://handbrake.fr)">
//   This file is part of the HandBrake source code - It may be used under the terms of the GNU General Public License.
// </copyright>
// <auto-generated> Disable Stylecop Warnings for this file  </auto-generated>
// --------------------------------------------------------------------------------------------------------------------

namespace HandBrake.Interop.HbLib
{
	using System;
	using System.Runtime.InteropServices;

	[StructLayout(LayoutKind.Sequential)]
	public struct hb_title_set_s
	{
		///hb_list_t   *
		public IntPtr list_title;

		// int
		public int feature;
	}
}
