HB_BUILD = $(shell date "+%Y%m%d")00
HB_VERSION = "0.8.0b2"
HB_DEFPPC = $(shell uname -a | grep ppc > /dev/null ; echo RES$$?)
ifeq ($(HB_DEFPPC), RES0)
HB_DEFPPC = "-DWORDS_BIGENDIAN"
else
HB_DEFPPC = " "
endif

