SNAP = $(shell echo $$SNAPSHOT)
ifeq ($(SNAP), 1)
HB_BUILD = $(shell date "+%Y%m%d")00
HB_VERSION = 0.9.0s$(shell date "+%d")
else
HB_BUILD = $(shell date "+%Y%m%d")00
HB_VERSION = "0.9.0"
endif
HB_DEFPPC = $(shell uname -a | grep ppc > /dev/null ; echo RES$$?)
ifeq ($(HB_DEFPPC), RES0)
HB_DEFPPC = "-DWORDS_BIGENDIAN"
else
HB_DEFPPC = 
endif

