# This line needs to be manually bumped for each release.
HB_VERSION = 0.9.3

# Use the current date for the build number
HB_BUILD = $(shell date "+%Y%m%d")00

# Do the same for snapshots but mark as unstable
SNAP_HB_BUILD = $(shell date "+%Y%m%d")01

# For snapshots add the svn revision number to the HB_VERSION
SNAP_HB_VERSION = $(HB_VERSION)svn$(shell svnversion)

# The working path is needed for editing the MacGui .plist
FULL_PATH = $(shell pwd)
BUILD_DATE = $(shell date "+%Y%m%d")

HB_DEFPPC = $(shell uname -a | grep ppc > /dev/null ; echo RES$$?)
ifeq ($(HB_DEFPPC), RES0)
HB_DEFPPC = "-DWORDS_BIGENDIAN"
else
HB_DEFPPC = 
endif
