"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
"<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">\n"
"<plist version=\"1.0\">\n"
"<dict>\n"
"	<key>Initialization</key>\n"
"	<dict>\n"
"		<key>crop_bottom</key>\n"
"		<integer>0</integer>\n"
"		<key>crop_left</key>\n"
"		<integer>0</integer>\n"
"		<key>crop_right</key>\n"
"		<integer>0</integer>\n"
"		<key>crop_top</key>\n"
"		<integer>0</integer>\n"
"		<key>end_chapter</key>\n"
"		<integer>100</integer>\n"
"		<key>preset</key>\n"
"		<string>Normal</string>\n"
"		<key>scale_height</key>\n"
"		<integer>480</integer>\n"
"		<key>scale_width</key>\n"
"		<integer>720</integer>\n"
"		<key>start_chapter</key>\n"
"		<integer>1</integer>\n"
"		<key>title</key>\n"
"		<string>none</string>\n"
"		<key>volume_label</key>\n"
"		<string>New Video</string>\n"
"		<key>x264_8x8dct</key>\n"
"		<false />\n"
"		<key>x264_analyse</key>\n"
"		<string>some</string>\n"
"		<key>x264_bframes</key>\n"
"		<integer>0</integer>\n"
"		<key>x264_bime</key>\n"
"		<false />\n"
"		<key>x264_bpyramid</key>\n"
"		<false />\n"
"		<key>x264_brdo</key>\n"
"		<false />\n"
"		<key>x264_cabac</key>\n"
"		<true />\n"
"		<key>x264_deblock_alpha</key>\n"
"		<integer>0</integer>\n"
"		<key>x264_deblock_beta</key>\n"
"		<integer>0</integer>\n"
"		<key>x264_direct</key>\n"
"		<string>spatial</string>\n"
"		<key>x264_me</key>\n"
"		<string>hex</string>\n"
"		<key>x264_merange</key>\n"
"		<integer>16</integer>\n"
"		<key>x264_mixed_refs</key>\n"
"		<false />\n"
"		<key>x264_no_dct_decimate</key>\n"
"		<false />\n"
"		<key>x264_no_fast_pskip</key>\n"
"		<false />\n"
"		<key>x264_refs</key>\n"
"		<integer>1</integer>\n"
"		<key>x264_subme</key>\n"
"		<integer>5</integer>\n"
"		<key>x264_trellis</key>\n"
"		<integer>0</integer>\n"
"		<key>x264_weighted_bframes</key>\n"
"		<false />\n"
"		<key>audio_list</key>\n"
"		<array>\n"
"		</array>\n"
"	</dict>\n"
"	<key>Preferences</key>\n"
"	<dict>\n"
"		<key>allow_tweaks</key>\n"
"		<false />\n"
"		<key>default_preset</key>\n"
"		<string>Normal</string>\n"
"		<key>default_source</key>\n"
"		<string>/dev/dvd</string>\n"
"		<key>destination_dir</key>\n"
"		<string></string>\n"
"		<key>hbfd</key>\n"
"		<false />\n"
"		<key>hbfd_feature</key>\n"
"		<false />\n"
"		<key>linear_vquality</key>\n"
"		<false />\n"
"		<key>nocheckvquality</key>\n"
"		<false />\n"
"		<key>noscale</key>\n"
"		<false />\n"
"		<key>show_presets</key>\n"
"		<true />\n"
"		<key>use_source_name</key>\n"
"		<true />\n"
"		<key>version</key>\n"
"		<string>0.1</string>\n"
"	</dict>\n"
"	<key>Presets</key>\n"
"	<dict>\n"
"		<key>anamorphic</key>\n"
"		<true />\n"
"		<key>autocrop</key>\n"
"		<true />\n"
"		<key>autoscale</key>\n"
"		<true />\n"
"		<key>chapter_markers</key>\n"
"		<true />\n"
"		<key>constant_rate_factor</key>\n"
"		<true />\n"
"		<key>container</key>\n"
"		<string>mp4</string>\n"
"		<key>deblock</key>\n"
"		<false />\n"
"		<key>decomb</key>\n"
"		<true />\n"
"		<key>deinterlace</key>\n"
"		<string>none</string>\n"
"		<key>denoise</key>\n"
"		<string>none</string>\n"
"		<key>detelecine</key>\n"
"		<true />\n"
"		<key>directqp</key>\n"
"		<false />\n"
"		<key>forced_subtitles</key>\n"
"		<true />\n"
"		<key>framerate</key>\n"
"		<string>source</string>\n"
"		<key>grayscale</key>\n"
"		<false />\n"
"		<key>http_optimize_mp4</key>\n"
"		<false />\n"
"		<key>ipod_file</key>\n"
"		<false />\n"
"		<key>keep_aspect</key>\n"
"		<true />\n"
"		<key>large_mp4</key>\n"
"		<false />\n"
"		<key>max_height</key>\n"
"		<integer>0</integer>\n"
"		<key>max_width</key>\n"
"		<integer>0</integer>\n"
"		<key>pref_audio_list</key>\n"
"		<array>\n"
"			<dict>\n"
"				<key>audio_bitrate</key>\n"
"				<string>192</string>\n"
"				<key>audio_codec</key>\n"
"				<string>ac3</string>\n"
"				<key>audio_drc</key>\n"
"				<real>1</real>\n"
"				<key>audio_mix</key>\n"
"				<string>dpl2</string>\n"
"				<key>audio_rate</key>\n"
"				<string>source</string>\n"
"			</dict>\n"
"		</array>\n"
"		<key>preset_description</key>\n"
"		<string></string>\n"
"		<key>preset_type</key>\n"
"		<integer>1</integer>\n"
"		<key>round_dimensions</key>\n"
"		<true />\n"
"		<key>source_audio_lang</key>\n"
"		<string>und</string>\n"
"		<key>subtitle_lang</key>\n"
"		<string>none</string>\n"
"		<key>turbo</key>\n"
"		<false />\n"
"		<key>tweak_deblock</key>\n"
"		<string></string>\n"
"		<key>tweak_decomb</key>\n"
"		<string></string>\n"
"		<key>tweak_detelecine</key>\n"
"		<string></string>\n"
"		<key>two_pass</key>\n"
"		<false />\n"
"		<key>variable_frame_rate</key>\n"
"		<true />\n"
"		<key>video_bitrate</key>\n"
"		<integer>1800</integer>\n"
"		<key>video_codec</key>\n"
"		<string>x264</string>\n"
"		<key>video_quality</key>\n"
"		<integer>64</integer>\n"
"		<key>video_target_size</key>\n"
"		<integer>700</integer>\n"
"		<key>vquality_type_bitrate</key>\n"
"		<false />\n"
"		<key>vquality_type_constant</key>\n"
"		<false />\n"
"		<key>vquality_type_target</key>\n"
"		<false />\n"
"		<key>x264_options</key>\n"
"		<string></string>\n"
"	</dict>\n"
"</dict>\n"
"</plist>\n"
