"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
"<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">\n"
"<plist version=\"1.0\">\n"
"<dict>\n"
"	<key>Animation</key>\n"
"	<dict>\n"
"		<key>anamorphic</key>\n"
"		<true />\n"
"		<key>autocrop</key>\n"
"		<true />\n"
"		<key>autoscale</key>\n"
"		<true />\n"
"		<key>chapter_markers</key>\n"
"		<true />\n"
"		<key>container</key>\n"
"		<string>mkv</string>\n"
"		<key>deblock</key>\n"
"		<false />\n"
"		<key>decomb</key>\n"
"		<false />\n"
"		<key>deinterlace</key>\n"
"		<string>slower</string>\n"
"		<key>denoise</key>\n"
"		<integer>0</integer>\n"
"		<key>detelecine</key>\n"
"		<false />\n"
"		<key>framerate</key>\n"
"		<string>source</string>\n"
"		<key>grayscale</key>\n"
"		<false />\n"
"		<key>keep_aspect</key>\n"
"		<false />\n"
"		<key>max_height</key>\n"
"		<integer>0</integer>\n"
"		<key>max_width</key>\n"
"		<integer>0</integer>\n"
"		<key>pref_audio_list</key>\n"
"		<array>\n"
"			<dict>\n"
"				<key>audio_bitrate</key>\n"
"				<string>160</string>\n"
"				<key>audio_codec</key>\n"
"				<string>faac</string>\n"
"				<key>audio_drc</key>\n"
"				<real>1</real>\n"
"				<key>audio_mix</key>\n"
"				<string>dpl2</string>\n"
"				<key>audio_rate</key>\n"
"				<string>source</string>\n"
"			</dict>\n"
"		</array>\n"
"		<key>preset_description</key>\n"
"		<string>HandBrake's settings for cartoons, anime, and CGI.</string>\n"
"		<key>preset_type</key>\n"
"		<integer>0</integer>\n"
"		<key>subtitle_lang</key>\n"
"		<string>none</string>\n"
"		<key>turbo</key>\n"
"		<true />\n"
"		<key>two_pass</key>\n"
"		<true />\n"
"		<key>variable_frame_rate</key>\n"
"		<false />\n"
"		<key>video_bitrate</key>\n"
"		<integer>1000</integer>\n"
"		<key>video_codec</key>\n"
"		<string>x264</string>\n"
"		<key>video_quality</key>\n"
"		<integer>64</integer>\n"
"		<key>video_target_size</key>\n"
"		<integer>700</integer>\n"
"		<key>vquality_type_bitrate</key>\n"
"		<true />\n"
"		<key>x264_options</key>\n"
"		<string>ref=5:mixed-refs:bframes=6:bime:weightb:b-rdo:direct=auto:b-pyramid:me=umh:subme=5:analyse=all:8x8dct:trellis=1:nr=150:no-fast-pskip:filter=2,2</string>\n"
"	</dict>\n"
"	<key>AppleTV</key>\n"
"	<dict>\n"
"		<key>anamorphic</key>\n"
"		<true />\n"
"		<key>autoscale</key>\n"
"		<true />\n"
"		<key>chapter_markers</key>\n"
"		<true />\n"
"		<key>container</key>\n"
"		<string>mp4</string>\n"
"		<key>deblock</key>\n"
"		<false />\n"
"		<key>decomb</key>\n"
"		<false />\n"
"		<key>deinterlace</key>\n"
"		<string>none</string>\n"
"		<key>denoise</key>\n"
"		<integer>0</integer>\n"
"		<key>detelecine</key>\n"
"		<false />\n"
"		<key>framerate</key>\n"
"		<string>source</string>\n"
"		<key>grayscale</key>\n"
"		<false />\n"
"		<key>keep_aspect</key>\n"
"		<false />\n"
"		<key>large_mp4</key>\n"
"		<true />\n"
"		<key>max_height</key>\n"
"		<integer>0</integer>\n"
"		<key>max_width</key>\n"
"		<integer>0</integer>\n"
"		<key>pref_audio_list</key>\n"
"		<array>\n"
"			<dict>\n"
"				<key>audio_bitrate</key>\n"
"				<string>160</string>\n"
"				<key>audio_codec</key>\n"
"				<string>faac</string>\n"
"				<key>audio_drc</key>\n"
"				<real>1</real>\n"
"				<key>audio_mix</key>\n"
"				<string>dpl2</string>\n"
"				<key>audio_rate</key>\n"
"				<string>48</string>\n"
"			</dict>\n"
"			<dict>\n"
"				<key>audio_bitrate</key>\n"
"				<string>160</string>\n"
"				<key>audio_codec</key>\n"
"				<string>ac3</string>\n"
"				<key>audio_drc</key>\n"
"				<real>1</real>\n"
"				<key>audio_mix</key>\n"
"				<string>none</string>\n"
"				<key>audio_rate</key>\n"
"				<string>source</string>\n"
"			</dict>\n"
"		</array>\n"
"		<key>preset_description</key>\n"
"		<string>HandBrake's settings for the AppleTV, including Dolby Digital 5.1 AC3 sound. Provides a good balance between quality and file size, and optimizes performance.</string>\n"
"		<key>preset_type</key>\n"
"		<integer>0</integer>\n"
"		<key>subtitle_lang</key>\n"
"		<string>none</string>\n"
"		<key>two_pass</key>\n"
"		<false />\n"
"		<key>variable_frame_rate</key>\n"
"		<false />\n"
"		<key>video_bitrate</key>\n"
"		<integer>2500</integer>\n"
"		<key>video_codec</key>\n"
"		<string>x264</string>\n"
"		<key>video_quality</key>\n"
"		<integer>64</integer>\n"
"		<key>video_target_size</key>\n"
"		<integer>700</integer>\n"
"		<key>vquality_type_bitrate</key>\n"
"		<true />\n"
"		<key>x264_options</key>\n"
"		<string>bframes=3:ref=1:subme=5:me=umh:no-fast-pskip=1:trellis=1:cabac=0</string>\n"
"	</dict>\n"
"	<key>Bedlam</key>\n"
"	<dict>\n"
"		<key>anamorphic</key>\n"
"		<true />\n"
"		<key>autocrop</key>\n"
"		<true />\n"
"		<key>autoscale</key>\n"
"		<true />\n"
"		<key>chapter_markers</key>\n"
"		<true />\n"
"		<key>container</key>\n"
"		<string>mkv</string>\n"
"		<key>deblock</key>\n"
"		<false />\n"
"		<key>decomb</key>\n"
"		<false />\n"
"		<key>deinterlace</key>\n"
"		<string>none</string>\n"
"		<key>denoise</key>\n"
"		<integer>0</integer>\n"
"		<key>detelecine</key>\n"
"		<false />\n"
"		<key>framerate</key>\n"
"		<string>source</string>\n"
"		<key>grayscale</key>\n"
"		<false />\n"
"		<key>keep_aspect</key>\n"
"		<false />\n"
"		<key>max_height</key>\n"
"		<integer>0</integer>\n"
"		<key>max_width</key>\n"
"		<integer>0</integer>\n"
"		<key>pref_audio_list</key>\n"
"		<array>\n"
"			<dict>\n"
"				<key>audio_bitrate</key>\n"
"				<string>160</string>\n"
"				<key>audio_codec</key>\n"
"				<string>ac3</string>\n"
"				<key>audio_drc</key>\n"
"				<real>1</real>\n"
"				<key>audio_mix</key>\n"
"				<string>none</string>\n"
"				<key>audio_rate</key>\n"
"				<string>source</string>\n"
"			</dict>\n"
"		</array>\n"
"		<key>preset_description</key>\n"
"		<string>HandBrake's settings maxed out for slowest encoding and highest quality. Use at your own risk. So slow it's not just insane...it's a trip to the looney bin.</string>\n"
"		<key>preset_type</key>\n"
"		<integer>0</integer>\n"
"		<key>subtitle_lang</key>\n"
"		<string>none</string>\n"
"		<key>turbo</key>\n"
"		<true />\n"
"		<key>two_pass</key>\n"
"		<true />\n"
"		<key>variable_frame_rate</key>\n"
"		<false />\n"
"		<key>video_bitrate</key>\n"
"		<integer>1800</integer>\n"
"		<key>video_codec</key>\n"
"		<string>x264</string>\n"
"		<key>video_quality</key>\n"
"		<integer>64</integer>\n"
"		<key>video_target_size</key>\n"
"		<integer>700</integer>\n"
"		<key>vquality_type_bitrate</key>\n"
"		<true />\n"
"		<key>x264_options</key>\n"
"		<string>ref=16:mixed-refs:bframes=16:bime:weightb:b-rdo:direct=auto:b-pyramid:me=esa:subme=7:me-range=64:analyse=all:8x8dct:trellis=1:no-fast-pskip:no-dct-decimate:filter=-2,-1</string>\n"
"	</dict>\n"
"	<key>Blind</key>\n"
"	<dict>\n"
"		<key>anamorphic</key>\n"
"		<false />\n"
"		<key>autocrop</key>\n"
"		<true />\n"
"		<key>autoscale</key>\n"
"		<false />\n"
"		<key>chapter_markers</key>\n"
"		<true />\n"
"		<key>container</key>\n"
"		<string>mp4</string>\n"
"		<key>deblock</key>\n"
"		<false />\n"
"		<key>decomb</key>\n"
"		<false />\n"
"		<key>deinterlace</key>\n"
"		<string>none</string>\n"
"		<key>denoise</key>\n"
"		<integer>0</integer>\n"
"		<key>detelecine</key>\n"
"		<false />\n"
"		<key>framerate</key>\n"
"		<string>source</string>\n"
"		<key>grayscale</key>\n"
"		<false />\n"
"		<key>keep_aspect</key>\n"
"		<true />\n"
"		<key>max_height</key>\n"
"		<integer>0</integer>\n"
"		<key>max_width</key>\n"
"		<integer>512</integer>\n"
"		<key>pref_audio_list</key>\n"
"		<array>\n"
"			<dict>\n"
"				<key>audio_bitrate</key>\n"
"				<string>128</string>\n"
"				<key>audio_codec</key>\n"
"				<string>faac</string>\n"
"				<key>audio_drc</key>\n"
"				<real>1</real>\n"
"				<key>audio_mix</key>\n"
"				<string>dpl2</string>\n"
"				<key>audio_rate</key>\n"
"				<string>source</string>\n"
"			</dict>\n"
"		</array>\n"
"		<key>preset_description</key>\n"
"		<string>HandBrake's preset for impatient people who don't care about picture quality.</string>\n"
"		<key>preset_type</key>\n"
"		<integer>0</integer>\n"
"		<key>subtitle_lang</key>\n"
"		<string>none</string>\n"
"		<key>turbo</key>\n"
"		<false />\n"
"		<key>two_pass</key>\n"
"		<false />\n"
"		<key>variable_frame_rate</key>\n"
"		<false />\n"
"		<key>video_bitrate</key>\n"
"		<integer>512</integer>\n"
"		<key>video_codec</key>\n"
"		<string>ffmpeg</string>\n"
"		<key>video_quality</key>\n"
"		<integer>64</integer>\n"
"		<key>video_target_size</key>\n"
"		<integer>700</integer>\n"
"		<key>vquality_type_bitrate</key>\n"
"		<true />\n"
"		<key>x264_options</key>\n"
"		<string></string>\n"
"	</dict>\n"
"	<key>Broke</key>\n"
"	<dict>\n"
"		<key>anamorphic</key>\n"
"		<false />\n"
"		<key>autocrop</key>\n"
"		<true />\n"
"		<key>autoscale</key>\n"
"		<false />\n"
"		<key>chapter_markers</key>\n"
"		<true />\n"
"		<key>container</key>\n"
"		<string>mp4</string>\n"
"		<key>deblock</key>\n"
"		<false />\n"
"		<key>decomb</key>\n"
"		<false />\n"
"		<key>deinterlace</key>\n"
"		<string>none</string>\n"
"		<key>denoise</key>\n"
"		<integer>0</integer>\n"
"		<key>detelecine</key>\n"
"		<false />\n"
"		<key>framerate</key>\n"
"		<string>source</string>\n"
"		<key>grayscale</key>\n"
"		<false />\n"
"		<key>keep_aspect</key>\n"
"		<true />\n"
"		<key>max_height</key>\n"
"		<integer>0</integer>\n"
"		<key>max_width</key>\n"
"		<integer>640</integer>\n"
"		<key>pref_audio_list</key>\n"
"		<array>\n"
"			<dict>\n"
"				<key>audio_bitrate</key>\n"
"				<string>128</string>\n"
"				<key>audio_codec</key>\n"
"				<string>faac</string>\n"
"				<key>audio_drc</key>\n"
"				<real>1</real>\n"
"				<key>audio_mix</key>\n"
"				<string>dpl2</string>\n"
"				<key>audio_rate</key>\n"
"				<string>source</string>\n"
"			</dict>\n"
"		</array>\n"
"		<key>preset_description</key>\n"
"		<string>HandBrake's preset for people without a lot of money to waste on hard drives. Tries to maximize quality for burning to CDs, so you can party like it's 1999.</string>\n"
"		<key>preset_type</key>\n"
"		<integer>0</integer>\n"
"		<key>subtitle_lang</key>\n"
"		<string>none</string>\n"
"		<key>turbo</key>\n"
"		<true />\n"
"		<key>two_pass</key>\n"
"		<true />\n"
"		<key>variable_frame_rate</key>\n"
"		<false />\n"
"		<key>video_bitrate</key>\n"
"		<integer>1600</integer>\n"
"		<key>video_codec</key>\n"
"		<string>x264</string>\n"
"		<key>video_quality</key>\n"
"		<integer>64</integer>\n"
"		<key>video_target_size</key>\n"
"		<integer>695</integer>\n"
"		<key>vquality_type_target</key>\n"
"		<true />\n"
"		<key>x264_options</key>\n"
"		<string>ref=3:mixed-refs:bframes=16:bime:weightb:b-rdo:b-pyramid:direct=auto:me=umh:subme=6:trellis=1:analyse=all:8x8dct:no-fast-pskip</string>\n"
"	</dict>\n"
"	<key>Classic</key>\n"
"	<dict>\n"
"		<key>anamorphic</key>\n"
"		<false />\n"
"		<key>autocrop</key>\n"
"		<true />\n"
"		<key>autoscale</key>\n"
"		<true />\n"
"		<key>chapter_markers</key>\n"
"		<false />\n"
"		<key>container</key>\n"
"		<string>mp4</string>\n"
"		<key>deblock</key>\n"
"		<false />\n"
"		<key>decomb</key>\n"
"		<false />\n"
"		<key>deinterlace</key>\n"
"		<string>none</string>\n"
"		<key>denoise</key>\n"
"		<integer>0</integer>\n"
"		<key>detelecine</key>\n"
"		<false />\n"
"		<key>framerate</key>\n"
"		<string>source</string>\n"
"		<key>grayscale</key>\n"
"		<false />\n"
"		<key>keep_aspect</key>\n"
"		<true />\n"
"		<key>max_height</key>\n"
"		<integer>0</integer>\n"
"		<key>max_width</key>\n"
"		<integer>0</integer>\n"
"		<key>pref_audio_list</key>\n"
"		<array>\n"
"			<dict>\n"
"				<key>audio_bitrate</key>\n"
"				<string>160</string>\n"
"				<key>audio_codec</key>\n"
"				<string>faac</string>\n"
"				<key>audio_drc</key>\n"
"				<real>1</real>\n"
"				<key>audio_mix</key>\n"
"				<string>dpl2</string>\n"
"				<key>audio_rate</key>\n"
"				<string>source</string>\n"
"			</dict>\n"
"		</array>\n"
"		<key>preset_description</key>\n"
"		<string>HandBrake's traditional, faster, lower-quality settings.</string>\n"
"		<key>preset_type</key>\n"
"		<integer>0</integer>\n"
"		<key>subtitle_lang</key>\n"
"		<string>none</string>\n"
"		<key>two_pass</key>\n"
"		<false />\n"
"		<key>variable_frame_rate</key>\n"
"		<false />\n"
"		<key>video_bitrate</key>\n"
"		<integer>1000</integer>\n"
"		<key>video_codec</key>\n"
"		<string>ffmpeg</string>\n"
"		<key>video_quality</key>\n"
"		<integer>64</integer>\n"
"		<key>video_target_size</key>\n"
"		<integer>700</integer>\n"
"		<key>vquality_type_bitrate</key>\n"
"		<true />\n"
"		<key>x264_options</key>\n"
"		<string></string>\n"
"	</dict>\n"
"	<key>Constant Quality Rate</key>\n"
"	<dict>\n"
"		<key>anamorphic</key>\n"
"		<true />\n"
"		<key>autocrop</key>\n"
"		<true />\n"
"		<key>autoscale</key>\n"
"		<true />\n"
"		<key>chapter_markers</key>\n"
"		<true />\n"
"		<key>container</key>\n"
"		<string>mkv</string>\n"
"		<key>deblock</key>\n"
"		<false />\n"
"		<key>decomb</key>\n"
"		<false />\n"
"		<key>deinterlace</key>\n"
"		<string>none</string>\n"
"		<key>denoise</key>\n"
"		<integer>0</integer>\n"
"		<key>detelecine</key>\n"
"		<false />\n"
"		<key>framerate</key>\n"
"		<string>source</string>\n"
"		<key>grayscale</key>\n"
"		<false />\n"
"		<key>keep_aspect</key>\n"
"		<false />\n"
"		<key>max_height</key>\n"
"		<integer>0</integer>\n"
"		<key>max_width</key>\n"
"		<integer>0</integer>\n"
"		<key>pref_audio_list</key>\n"
"		<array>\n"
"			<dict>\n"
"				<key>audio_bitrate</key>\n"
"				<string>160</string>\n"
"				<key>audio_codec</key>\n"
"				<string>ac3</string>\n"
"				<key>audio_drc</key>\n"
"				<real>1</real>\n"
"				<key>audio_mix</key>\n"
"				<string>none</string>\n"
"				<key>audio_rate</key>\n"
"				<string>source</string>\n"
"			</dict>\n"
"		</array>\n"
"		<key>preset_description</key>\n"
"		<string>HandBrake's preset for consistently excellent quality in one pass, with the downside of entirely unpredictable file sizes and bitrates.</string>\n"
"		<key>preset_type</key>\n"
"		<integer>0</integer>\n"
"		<key>subtitle_lang</key>\n"
"		<string>none</string>\n"
"		<key>turbo</key>\n"
"		<false />\n"
"		<key>two_pass</key>\n"
"		<false />\n"
"		<key>variable_frame_rate</key>\n"
"		<false />\n"
"		<key>video_bitrate</key>\n"
"		<integer>2000</integer>\n"
"		<key>video_codec</key>\n"
"		<string>x264</string>\n"
"		<key>video_quality</key>\n"
"		<integer>64</integer>\n"
"		<key>video_target_size</key>\n"
"		<integer>700</integer>\n"
"		<key>vquality_type_constant</key>\n"
"		<true />\n"
"		<key>x264_options</key>\n"
"		<string>ref=3:mixed-refs:bframes=3:b-pyramid:b-rdo:bime:weightb:filter=-2,-1:subme=6:trellis=1:analyse=all:8x8dct:me=umh</string>\n"
"	</dict>\n"
"	<key>Deux Six Quatre</key>\n"
"	<dict>\n"
"		<key>anamorphic</key>\n"
"		<true />\n"
"		<key>autocrop</key>\n"
"		<true />\n"
"		<key>autoscale</key>\n"
"		<true />\n"
"		<key>chapter_markers</key>\n"
"		<true />\n"
"		<key>container</key>\n"
"		<string>mkv</string>\n"
"		<key>deblock</key>\n"
"		<false />\n"
"		<key>decomb</key>\n"
"		<false />\n"
"		<key>deinterlace</key>\n"
"		<string>none</string>\n"
"		<key>denoise</key>\n"
"		<integer>0</integer>\n"
"		<key>detelecine</key>\n"
"		<false />\n"
"		<key>framerate</key>\n"
"		<string>source</string>\n"
"		<key>grayscale</key>\n"
"		<false />\n"
"		<key>keep_aspect</key>\n"
"		<false />\n"
"		<key>max_height</key>\n"
"		<integer>0</integer>\n"
"		<key>max_width</key>\n"
"		<integer>0</integer>\n"
"		<key>pref_audio_list</key>\n"
"		<array>\n"
"			<dict>\n"
"				<key>audio_bitrate</key>\n"
"				<string>160</string>\n"
"				<key>audio_codec</key>\n"
"				<string>ac3</string>\n"
"				<key>audio_drc</key>\n"
"				<real>1</real>\n"
"				<key>audio_mix</key>\n"
"				<string>none</string>\n"
"				<key>audio_rate</key>\n"
"				<string>source</string>\n"
"			</dict>\n"
"		</array>\n"
"		<key>preset_description</key>\n"
"		<string>HandBrake's preset for true high profile x264 quality. A good balance of quality and speed, based on community standards found in the wild. This preset will give you a much better sense of x264's capabilities than vanilla main profile.</string>\n"
"		<key>preset_type</key>\n"
"		<integer>0</integer>\n"
"		<key>subtitle_lang</key>\n"
"		<string>none</string>\n"
"		<key>turbo</key>\n"
"		<true />\n"
"		<key>two_pass</key>\n"
"		<true />\n"
"		<key>variable_frame_rate</key>\n"
"		<false />\n"
"		<key>video_bitrate</key>\n"
"		<integer>1600</integer>\n"
"		<key>video_codec</key>\n"
"		<string>x264</string>\n"
"		<key>video_quality</key>\n"
"		<integer>64</integer>\n"
"		<key>video_target_size</key>\n"
"		<integer>700</integer>\n"
"		<key>vquality_type_bitrate</key>\n"
"		<true />\n"
"		<key>x264_options</key>\n"
"		<string>ref=5:mixed-refs:bframes=3:bime:weightb:b-rdo:b-pyramid:me=umh:subme=7:trellis=1:analyse=all:8x8dct:no-fast-pskip</string>\n"
"	</dict>\n"
"	<key>Film</key>\n"
"	<dict>\n"
"		<key>anamorphic</key>\n"
"		<true />\n"
"		<key>autocrop</key>\n"
"		<true />\n"
"		<key>autoscale</key>\n"
"		<true />\n"
"		<key>chapter_markers</key>\n"
"		<true />\n"
"		<key>container</key>\n"
"		<string>mkv</string>\n"
"		<key>deblock</key>\n"
"		<false />\n"
"		<key>decomb</key>\n"
"		<false />\n"
"		<key>deinterlace</key>\n"
"		<string>none</string>\n"
"		<key>denoise</key>\n"
"		<integer>0</integer>\n"
"		<key>detelecine</key>\n"
"		<false />\n"
"		<key>framerate</key>\n"
"		<string>source</string>\n"
"		<key>grayscale</key>\n"
"		<false />\n"
"		<key>keep_aspect</key>\n"
"		<false />\n"
"		<key>max_height</key>\n"
"		<integer>0</integer>\n"
"		<key>max_width</key>\n"
"		<integer>0</integer>\n"
"		<key>pref_audio_list</key>\n"
"		<array>\n"
"			<dict>\n"
"				<key>audio_bitrate</key>\n"
"				<string>160</string>\n"
"				<key>audio_codec</key>\n"
"				<string>ac3</string>\n"
"				<key>audio_drc</key>\n"
"				<real>1</real>\n"
"				<key>audio_mix</key>\n"
"				<string>none</string>\n"
"				<key>audio_rate</key>\n"
"				<string>source</string>\n"
"			</dict>\n"
"		</array>\n"
"		<key>preset_description</key>\n"
"		<string>HandBrake's preset for feature films.</string>\n"
"		<key>preset_type</key>\n"
"		<integer>0</integer>\n"
"		<key>subtitle_lang</key>\n"
"		<string>none</string>\n"
"		<key>turbo</key>\n"
"		<true />\n"
"		<key>two_pass</key>\n"
"		<true />\n"
"		<key>variable_frame_rate</key>\n"
"		<false />\n"
"		<key>video_bitrate</key>\n"
"		<integer>1800</integer>\n"
"		<key>video_codec</key>\n"
"		<string>x264</string>\n"
"		<key>video_quality</key>\n"
"		<integer>64</integer>\n"
"		<key>video_target_size</key>\n"
"		<integer>700</integer>\n"
"		<key>vquality_type_bitrate</key>\n"
"		<true />\n"
"		<key>x264_options</key>\n"
"		<string>ref=3:mixed-refs:bframes=6:bime:weightb:b-rdo:direct=auto:b-pyramid:me=umh:subme=7:analyse=all:8x8dct:trellis=1:no-fast-pskip</string>\n"
"	</dict>\n"
"	<key>Normal</key>\n"
"	<dict>\n"
"		<key>anamorphic</key>\n"
"		<true />\n"
"		<key>autocrop</key>\n"
"		<true />\n"
"		<key>autoscale</key>\n"
"		<true />\n"
"		<key>chapter_markers</key>\n"
"		<true />\n"
"		<key>container</key>\n"
"		<string>mp4</string>\n"
"		<key>deblock</key>\n"
"		<false />\n"
"		<key>decomb</key>\n"
"		<false />\n"
"		<key>deinterlace</key>\n"
"		<string>none</string>\n"
"		<key>denoise</key>\n"
"		<integer>0</integer>\n"
"		<key>detelecine</key>\n"
"		<false />\n"
"		<key>framerate</key>\n"
"		<string>source</string>\n"
"		<key>grayscale</key>\n"
"		<false />\n"
"		<key>keep_aspect</key>\n"
"		<false />\n"
"		<key>max_height</key>\n"
"		<integer>0</integer>\n"
"		<key>max_width</key>\n"
"		<integer>0</integer>\n"
"		<key>pref_audio_list</key>\n"
"		<array>\n"
"			<dict>\n"
"				<key>audio_bitrate</key>\n"
"				<string>160</string>\n"
"				<key>audio_codec</key>\n"
"				<string>faac</string>\n"
"				<key>audio_drc</key>\n"
"				<real>1</real>\n"
"				<key>audio_mix</key>\n"
"				<string>dpl2</string>\n"
"				<key>audio_rate</key>\n"
"				<string>source</string>\n"
"			</dict>\n"
"		</array>\n"
"		<key>preset_description</key>\n"
"		<string>HandBrake's normal, default settings.</string>\n"
"		<key>preset_type</key>\n"
"		<integer>0</integer>\n"
"		<key>subtitle_lang</key>\n"
"		<string>none</string>\n"
"		<key>turbo</key>\n"
"		<true />\n"
"		<key>two_pass</key>\n"
"		<true />\n"
"		<key>variable_frame_rate</key>\n"
"		<false />\n"
"		<key>video_bitrate</key>\n"
"		<integer>1500</integer>\n"
"		<key>video_codec</key>\n"
"		<string>x264</string>\n"
"		<key>video_quality</key>\n"
"		<integer>64</integer>\n"
"		<key>video_target_size</key>\n"
"		<integer>700</integer>\n"
"		<key>vquality_type_bitrate</key>\n"
"		<true />\n"
"		<key>x264_options</key>\n"
"		<string>ref=2:bframes=2:subme=5:me=umh</string>\n"
"	</dict>\n"
"	<key>PS3</key>\n"
"	<dict>\n"
"		<key>anamorphic</key>\n"
"		<true />\n"
"		<key>autoscale</key>\n"
"		<true />\n"
"		<key>chapter_markers</key>\n"
"		<false />\n"
"		<key>container</key>\n"
"		<string>mp4</string>\n"
"		<key>deblock</key>\n"
"		<false />\n"
"		<key>decomb</key>\n"
"		<false />\n"
"		<key>deinterlace</key>\n"
"		<string>none</string>\n"
"		<key>denoise</key>\n"
"		<integer>0</integer>\n"
"		<key>detelecine</key>\n"
"		<false />\n"
"		<key>framerate</key>\n"
"		<string>source</string>\n"
"		<key>grayscale</key>\n"
"		<false />\n"
"		<key>keep_aspect</key>\n"
"		<false />\n"
"		<key>max_height</key>\n"
"		<integer>0</integer>\n"
"		<key>max_width</key>\n"
"		<integer>0</integer>\n"
"		<key>pref_audio_list</key>\n"
"		<array>\n"
"			<dict>\n"
"				<key>audio_bitrate</key>\n"
"				<string>160</string>\n"
"				<key>audio_codec</key>\n"
"				<string>faac</string>\n"
"				<key>audio_drc</key>\n"
"				<real>1</real>\n"
"				<key>audio_mix</key>\n"
"				<string>dpl2</string>\n"
"				<key>audio_rate</key>\n"
"				<string>48</string>\n"
"			</dict>\n"
"		</array>\n"
"		<key>preset_description</key>\n"
"		<string>HandBrake's settings for the Sony PlayStation 3.</string>\n"
"		<key>preset_type</key>\n"
"		<integer>0</integer>\n"
"		<key>subtitle_lang</key>\n"
"		<string>none</string>\n"
"		<key>two_pass</key>\n"
"		<false />\n"
"		<key>variable_frame_rate</key>\n"
"		<false />\n"
"		<key>video_bitrate</key>\n"
"		<integer>2500</integer>\n"
"		<key>video_codec</key>\n"
"		<string>x264</string>\n"
"		<key>video_quality</key>\n"
"		<integer>64</integer>\n"
"		<key>video_target_size</key>\n"
"		<integer>700</integer>\n"
"		<key>vquality_type_bitrate</key>\n"
"		<true />\n"
"		<key>x264_options</key>\n"
"		<string>level=41:subme=5:me=umh</string>\n"
"	</dict>\n"
"	<key>PSP</key>\n"
"	<dict>\n"
"		<key>anamorphic</key>\n"
"		<false />\n"
"		<key>autocrop</key>\n"
"		<true />\n"
"		<key>autoscale</key>\n"
"		<false />\n"
"		<key>chapter_markers</key>\n"
"		<true />\n"
"		<key>container</key>\n"
"		<string>mp4</string>\n"
"		<key>deblock</key>\n"
"		<false />\n"
"		<key>decomb</key>\n"
"		<false />\n"
"		<key>deinterlace</key>\n"
"		<string>none</string>\n"
"		<key>denoise</key>\n"
"		<integer>0</integer>\n"
"		<key>detelecine</key>\n"
"		<false />\n"
"		<key>framerate</key>\n"
"		<string>source</string>\n"
"		<key>grayscale</key>\n"
"		<false />\n"
"		<key>keep_aspect</key>\n"
"		<true />\n"
"		<key>max_height</key>\n"
"		<integer>208</integer>\n"
"		<key>max_width</key>\n"
"		<integer>368</integer>\n"
"		<key>pref_audio_list</key>\n"
"		<array>\n"
"			<dict>\n"
"				<key>audio_bitrate</key>\n"
"				<string>128</string>\n"
"				<key>audio_codec</key>\n"
"				<string>faac</string>\n"
"				<key>audio_drc</key>\n"
"				<real>1</real>\n"
"				<key>audio_mix</key>\n"
"				<string>dpl2</string>\n"
"				<key>audio_rate</key>\n"
"				<string>48</string>\n"
"			</dict>\n"
"		</array>\n"
"		<key>preset_description</key>\n"
"		<string>HandBrake's settings for the Sony PlayStation Portable.</string>\n"
"		<key>preset_type</key>\n"
"		<integer>0</integer>\n"
"		<key>subtitle_lang</key>\n"
"		<string>none</string>\n"
"		<key>two_pass</key>\n"
"		<false />\n"
"		<key>variable_frame_rate</key>\n"
"		<false />\n"
"		<key>video_bitrate</key>\n"
"		<integer>1024</integer>\n"
"		<key>video_codec</key>\n"
"		<string>ffmpeg</string>\n"
"		<key>video_quality</key>\n"
"		<integer>64</integer>\n"
"		<key>video_target_size</key>\n"
"		<integer>700</integer>\n"
"		<key>vquality_type_bitrate</key>\n"
"		<true />\n"
"		<key>x264_options</key>\n"
"		<string></string>\n"
"	</dict>\n"
"	<key>QuickTime</key>\n"
"	<dict>\n"
"		<key>anamorphic</key>\n"
"		<true />\n"
"		<key>autocrop</key>\n"
"		<true />\n"
"		<key>autoscale</key>\n"
"		<true />\n"
"		<key>chapter_markers</key>\n"
"		<true />\n"
"		<key>container</key>\n"
"		<string>mp4</string>\n"
"		<key>deblock</key>\n"
"		<false />\n"
"		<key>decomb</key>\n"
"		<false />\n"
"		<key>deinterlace</key>\n"
"		<string>none</string>\n"
"		<key>denoise</key>\n"
"		<integer>0</integer>\n"
"		<key>detelecine</key>\n"
"		<false />\n"
"		<key>framerate</key>\n"
"		<string>source</string>\n"
"		<key>grayscale</key>\n"
"		<false />\n"
"		<key>keep_aspect</key>\n"
"		<false />\n"
"		<key>max_height</key>\n"
"		<integer>0</integer>\n"
"		<key>max_width</key>\n"
"		<integer>0</integer>\n"
"		<key>pref_audio_list</key>\n"
"		<array>\n"
"			<dict>\n"
"				<key>audio_bitrate</key>\n"
"				<string>160</string>\n"
"				<key>audio_codec</key>\n"
"				<string>faac</string>\n"
"				<key>audio_drc</key>\n"
"				<real>1</real>\n"
"				<key>audio_mix</key>\n"
"				<string>dpl2</string>\n"
"				<key>audio_rate</key>\n"
"				<string>source</string>\n"
"			</dict>\n"
"		</array>\n"
"		<key>preset_description</key>\n"
"		<string>HandBrake's high quality settings for use with QuickTime. It can be slow, so use it when the Normal preset doesn't look good enough.</string>\n"
"		<key>preset_type</key>\n"
"		<integer>0</integer>\n"
"		<key>subtitle_lang</key>\n"
"		<string>none</string>\n"
"		<key>turbo</key>\n"
"		<true />\n"
"		<key>two_pass</key>\n"
"		<true />\n"
"		<key>variable_frame_rate</key>\n"
"		<false />\n"
"		<key>video_bitrate</key>\n"
"		<integer>2000</integer>\n"
"		<key>video_codec</key>\n"
"		<string>x264</string>\n"
"		<key>video_quality</key>\n"
"		<integer>64</integer>\n"
"		<key>video_target_size</key>\n"
"		<integer>700</integer>\n"
"		<key>vquality_type_bitrate</key>\n"
"		<true />\n"
"		<key>x264_options</key>\n"
"		<string>ref=3:mixed-refs:bframes=3:bime:weightb:b-rdo:direct=auto:me=umh:subme=5:analyse=all:trellis=1:no-fast-pskip</string>\n"
"	</dict>\n"
"	<key>Television</key>\n"
"	<dict>\n"
"		<key>anamorphic</key>\n"
"		<false />\n"
"		<key>autocrop</key>\n"
"		<true />\n"
"		<key>autoscale</key>\n"
"		<true />\n"
"		<key>chapter_markers</key>\n"
"		<true />\n"
"		<key>container</key>\n"
"		<string>mkv</string>\n"
"		<key>deblock</key>\n"
"		<false />\n"
"		<key>decomb</key>\n"
"		<false />\n"
"		<key>deinterlace</key>\n"
"		<string>slower</string>\n"
"		<key>denoise</key>\n"
"		<integer>1</integer>\n"
"		<key>detelecine</key>\n"
"		<false />\n"
"		<key>framerate</key>\n"
"		<string>source</string>\n"
"		<key>grayscale</key>\n"
"		<false />\n"
"		<key>keep_aspect</key>\n"
"		<true />\n"
"		<key>max_height</key>\n"
"		<integer>0</integer>\n"
"		<key>max_width</key>\n"
"		<integer>0</integer>\n"
"		<key>pref_audio_list</key>\n"
"		<array>\n"
"			<dict>\n"
"				<key>audio_bitrate</key>\n"
"				<string>160</string>\n"
"				<key>audio_codec</key>\n"
"				<string>faac</string>\n"
"				<key>audio_drc</key>\n"
"				<real>1</real>\n"
"				<key>audio_mix</key>\n"
"				<string>dpl2</string>\n"
"				<key>audio_rate</key>\n"
"				<string>source</string>\n"
"			</dict>\n"
"		</array>\n"
"		<key>preset_description</key>\n"
"		<string>HandBrake's settings for video from television.</string>\n"
"		<key>preset_type</key>\n"
"		<integer>0</integer>\n"
"		<key>subtitle_lang</key>\n"
"		<string>none</string>\n"
"		<key>turbo</key>\n"
"		<true />\n"
"		<key>two_pass</key>\n"
"		<true />\n"
"		<key>variable_frame_rate</key>\n"
"		<false />\n"
"		<key>video_bitrate</key>\n"
"		<integer>1300</integer>\n"
"		<key>video_codec</key>\n"
"		<string>x264</string>\n"
"		<key>video_quality</key>\n"
"		<integer>64</integer>\n"
"		<key>video_target_size</key>\n"
"		<integer>700</integer>\n"
"		<key>vquality_type_bitrate</key>\n"
"		<true />\n"
"		<key>x264_options</key>\n"
"		<string>ref=3:mixed-refs:bframes=6:bime:weightb:direct=auto:b-pyramid:me=umh:subme=6:analyse=all:8x8dct:trellis=1:nr=150:no-fast-pskip</string>\n"
"	</dict>\n"
"	<key>Xbox 360</key>\n"
"	<dict>\n"
"		<key>anamorphic</key>\n"
"		<true />\n"
"		<key>autoscale</key>\n"
"		<true />\n"
"		<key>chapter_markers</key>\n"
"		<false />\n"
"		<key>container</key>\n"
"		<string>mp4</string>\n"
"		<key>deblock</key>\n"
"		<false />\n"
"		<key>decomb</key>\n"
"		<false />\n"
"		<key>deinterlace</key>\n"
"		<string>none</string>\n"
"		<key>denoise</key>\n"
"		<integer>0</integer>\n"
"		<key>detelecine</key>\n"
"		<false />\n"
"		<key>framerate</key>\n"
"		<string>source</string>\n"
"		<key>grayscale</key>\n"
"		<false />\n"
"		<key>keep_aspect</key>\n"
"		<false />\n"
"		<key>max_height</key>\n"
"		<integer>0</integer>\n"
"		<key>max_width</key>\n"
"		<integer>0</integer>\n"
"		<key>pref_audio_list</key>\n"
"		<array>\n"
"			<dict>\n"
"				<key>audio_bitrate</key>\n"
"				<string>160</string>\n"
"				<key>audio_codec</key>\n"
"				<string>faac</string>\n"
"				<key>audio_drc</key>\n"
"				<real>1</real>\n"
"				<key>audio_mix</key>\n"
"				<string>dpl2</string>\n"
"				<key>audio_rate</key>\n"
"				<string>48</string>\n"
"			</dict>\n"
"		</array>\n"
"		<key>preset_description</key>\n"
"		<string>HandBrake's settings for the Microsoft Xbox 360.</string>\n"
"		<key>preset_type</key>\n"
"		<integer>0</integer>\n"
"		<key>subtitle_lang</key>\n"
"		<string>none</string>\n"
"		<key>two_pass</key>\n"
"		<false />\n"
"		<key>variable_frame_rate</key>\n"
"		<false />\n"
"		<key>video_bitrate</key>\n"
"		<integer>2000</integer>\n"
"		<key>video_codec</key>\n"
"		<string>x264</string>\n"
"		<key>video_quality</key>\n"
"		<integer>64</integer>\n"
"		<key>video_target_size</key>\n"
"		<integer>700</integer>\n"
"		<key>vquality_type_bitrate</key>\n"
"		<true />\n"
"		<key>x264_options</key>\n"
"		<string>level=40:ref=2:mixed-refs:bframes=3:bime:weightb:b-rdo:direct=auto:b-pyramid:me=umh:subme=5:analyse=all:no-fast-pskip:filter=-2,-1</string>\n"
"	</dict>\n"
"	<key>iPhone / iPod Touch</key>\n"
"	<dict>\n"
"		<key>anamorphic</key>\n"
"		<false />\n"
"		<key>autocrop</key>\n"
"		<true />\n"
"		<key>autoscale</key>\n"
"		<false />\n"
"		<key>chapter_markers</key>\n"
"		<true />\n"
"		<key>container</key>\n"
"		<string>mp4</string>\n"
"		<key>deblock</key>\n"
"		<false />\n"
"		<key>decomb</key>\n"
"		<false />\n"
"		<key>deinterlace</key>\n"
"		<string>none</string>\n"
"		<key>denoise</key>\n"
"		<integer>0</integer>\n"
"		<key>detelecine</key>\n"
"		<false />\n"
"		<key>framerate</key>\n"
"		<string>source</string>\n"
"		<key>grayscale</key>\n"
"		<false />\n"
"		<key>ipod_file</key>\n"
"		<true />\n"
"		<key>keep_aspect</key>\n"
"		<true />\n"
"		<key>max_height</key>\n"
"		<integer>0</integer>\n"
"		<key>max_width</key>\n"
"		<integer>480</integer>\n"
"		<key>pref_audio_list</key>\n"
"		<array>\n"
"			<dict>\n"
"				<key>audio_bitrate</key>\n"
"				<string>128</string>\n"
"				<key>audio_codec</key>\n"
"				<string>faac</string>\n"
"				<key>audio_drc</key>\n"
"				<real>1</real>\n"
"				<key>audio_mix</key>\n"
"				<string>dpl2</string>\n"
"				<key>audio_rate</key>\n"
"				<string>48</string>\n"
"			</dict>\n"
"		</array>\n"
"		<key>preset_description</key>\n"
"		<string>HandBrake's settings for the iPhone and iPod Touch.</string>\n"
"		<key>preset_type</key>\n"
"		<integer>0</integer>\n"
"		<key>subtitle_lang</key>\n"
"		<string>none</string>\n"
"		<key>two_pass</key>\n"
"		<false />\n"
"		<key>variable_frame_rate</key>\n"
"		<false />\n"
"		<key>video_bitrate</key>\n"
"		<integer>960</integer>\n"
"		<key>video_codec</key>\n"
"		<string>x264</string>\n"
"		<key>video_quality</key>\n"
"		<integer>64</integer>\n"
"		<key>video_target_size</key>\n"
"		<integer>700</integer>\n"
"		<key>vquality_type_bitrate</key>\n"
"		<true />\n"
"		<key>x264_options</key>\n"
"		<string>level=30:cabac=0:ref=1:analyse=all:me=umh:subme=6:no-fast-pskip=1:trellis=1</string>\n"
"	</dict>\n"
"	<key>iPod High-Rez</key>\n"
"	<dict>\n"
"		<key>anamorphic</key>\n"
"		<false />\n"
"		<key>autocrop</key>\n"
"		<true />\n"
"		<key>autoscale</key>\n"
"		<false />\n"
"		<key>chapter_markers</key>\n"
"		<true />\n"
"		<key>container</key>\n"
"		<string>mp4</string>\n"
"		<key>deblock</key>\n"
"		<false />\n"
"		<key>decomb</key>\n"
"		<false />\n"
"		<key>deinterlace</key>\n"
"		<string>none</string>\n"
"		<key>denoise</key>\n"
"		<integer>0</integer>\n"
"		<key>detelecine</key>\n"
"		<false />\n"
"		<key>framerate</key>\n"
"		<string>source</string>\n"
"		<key>grayscale</key>\n"
"		<false />\n"
"		<key>ipod_file</key>\n"
"		<true />\n"
"		<key>keep_aspect</key>\n"
"		<true />\n"
"		<key>max_height</key>\n"
"		<integer>0</integer>\n"
"		<key>max_width</key>\n"
"		<integer>640</integer>\n"
"		<key>pref_audio_list</key>\n"
"		<array>\n"
"			<dict>\n"
"				<key>audio_bitrate</key>\n"
"				<string>160</string>\n"
"				<key>audio_codec</key>\n"
"				<string>faac</string>\n"
"				<key>audio_drc</key>\n"
"				<real>1</real>\n"
"				<key>audio_mix</key>\n"
"				<string>dpl2</string>\n"
"				<key>audio_rate</key>\n"
"				<string>48</string>\n"
"			</dict>\n"
"		</array>\n"
"		<key>preset_description</key>\n"
"		<string>HandBrake's high resolution settings for the iPod. Good video quality, great for viewing on a TV using your iPod</string>\n"
"		<key>preset_type</key>\n"
"		<integer>0</integer>\n"
"		<key>subtitle_lang</key>\n"
"		<string>none</string>\n"
"		<key>two_pass</key>\n"
"		<false />\n"
"		<key>variable_frame_rate</key>\n"
"		<false />\n"
"		<key>video_bitrate</key>\n"
"		<integer>1500</integer>\n"
"		<key>video_codec</key>\n"
"		<string>x264</string>\n"
"		<key>video_quality</key>\n"
"		<integer>64</integer>\n"
"		<key>video_target_size</key>\n"
"		<integer>700</integer>\n"
"		<key>vquality_type_bitrate</key>\n"
"		<true />\n"
"		<key>x264_options</key>\n"
"		<string>level=30:bframes=0:cabac=0:ref=1:vbv-maxrate=1500:vbv-bufsize=2000:analyse=all:me=umh:subme=6:no-fast-pskip=1</string>\n"
"	</dict>\n"
"	<key>iPod Low-Rez</key>\n"
"	<dict>\n"
"		<key>anamorphic</key>\n"
"		<false />\n"
"		<key>autocrop</key>\n"
"		<true />\n"
"		<key>autoscale</key>\n"
"		<false />\n"
"		<key>chapter_markers</key>\n"
"		<true />\n"
"		<key>container</key>\n"
"		<string>mp4</string>\n"
"		<key>deblock</key>\n"
"		<false />\n"
"		<key>decomb</key>\n"
"		<false />\n"
"		<key>deinterlace</key>\n"
"		<string>none</string>\n"
"		<key>denoise</key>\n"
"		<integer>0</integer>\n"
"		<key>detelecine</key>\n"
"		<false />\n"
"		<key>framerate</key>\n"
"		<string>source</string>\n"
"		<key>grayscale</key>\n"
"		<false />\n"
"		<key>ipod_file</key>\n"
"		<true />\n"
"		<key>keep_aspect</key>\n"
"		<true />\n"
"		<key>max_height</key>\n"
"		<integer>0</integer>\n"
"		<key>max_width</key>\n"
"		<integer>320</integer>\n"
"		<key>pref_audio_list</key>\n"
"		<array>\n"
"			<dict>\n"
"				<key>audio_bitrate</key>\n"
"				<string>160</string>\n"
"				<key>audio_codec</key>\n"
"				<string>faac</string>\n"
"				<key>audio_drc</key>\n"
"				<real>1</real>\n"
"				<key>audio_mix</key>\n"
"				<string>dpl2</string>\n"
"				<key>audio_rate</key>\n"
"				<string>48</string>\n"
"			</dict>\n"
"		</array>\n"
"		<key>preset_description</key>\n"
"		<string>HandBrake's low resolution settings for the iPod. Optimized for great playback on the iPod screen, with smaller file size.</string>\n"
"		<key>preset_type</key>\n"
"		<integer>0</integer>\n"
"		<key>subtitle_lang</key>\n"
"		<string>none</string>\n"
"		<key>two_pass</key>\n"
"		<false />\n"
"		<key>variable_frame_rate</key>\n"
"		<false />\n"
"		<key>video_bitrate</key>\n"
"		<integer>700</integer>\n"
"		<key>video_codec</key>\n"
"		<string>x264</string>\n"
"		<key>video_quality</key>\n"
"		<integer>64</integer>\n"
"		<key>video_target_size</key>\n"
"		<integer>700</integer>\n"
"		<key>vquality_type_bitrate</key>\n"
"		<true />\n"
"		<key>x264_options</key>\n"
"		<string>level=30:bframes=0:cabac=0:ref=1:vbv-maxrate=768:vbv-bufsize=2000:analyse=all:me=umh:subme=6:no-fast-pskip=1</string>\n"
"	</dict>\n"
"</dict>\n"
"</plist>\n"
