"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
"<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">\n"
"<plist version=\"1.0\">\n"
"<dict>\n"
"	<key>audio_bitrate</key>\n"
"	<array>\n"
"		<array>\n"
"			<string>audio_codec</string>\n"
"			<string>ac3</string>\n"
"			<true />\n"
"		</array>\n"
"	</array>\n"
"	<key>audio_drc</key>\n"
"	<array>\n"
"		<array>\n"
"			<string>audio_codec</string>\n"
"			<string>ac3</string>\n"
"			<true />\n"
"		</array>\n"
"	</array>\n"
"	<key>audio_mix</key>\n"
"	<array>\n"
"		<array>\n"
"			<string>audio_codec</string>\n"
"			<string>ac3</string>\n"
"			<true />\n"
"		</array>\n"
"	</array>\n"
"	<key>audio_rate</key>\n"
"	<array>\n"
"		<array>\n"
"			<string>audio_codec</string>\n"
"			<string>ac3</string>\n"
"			<true />\n"
"		</array>\n"
"	</array>\n"
"	<key>chapters_label</key>\n"
"	<array>\n"
"		<array>\n"
"			<string>title</string>\n"
"			<string>none</string>\n"
"			<true />\n"
"		</array>\n"
"	</array>\n"
"	<key>chapters_list</key>\n"
"	<array>\n"
"		<array>\n"
"			<string>chapter_markers</string>\n"
"			<string>TRUE</string>\n"
"			<false />\n"
"		</array>\n"
"	</array>\n"
"	<key>chapters_tab</key>\n"
"	<array>\n"
"		<array>\n"
"			<string>title</string>\n"
"			<string>none</string>\n"
"			<true />\n"
"		</array>\n"
"	</array>\n"
"	<key>constant_rate_factor</key>\n"
"	<array>\n"
"		<array>\n"
"			<string>vquality_type_constant</string>\n"
"			<string>TRUE</string>\n"
"			<false />\n"
"		</array>\n"
"	</array>\n"
"	<key>crop_bottom</key>\n"
"	<array>\n"
"		<array>\n"
"			<string>autocrop</string>\n"
"			<string>FALSE</string>\n"
"			<false />\n"
"		</array>\n"
"	</array>\n"
"	<key>crop_left</key>\n"
"	<array>\n"
"		<array>\n"
"			<string>autocrop</string>\n"
"			<string>FALSE</string>\n"
"			<false />\n"
"		</array>\n"
"	</array>\n"
"	<key>crop_right</key>\n"
"	<array>\n"
"		<array>\n"
"			<string>autocrop</string>\n"
"			<string>FALSE</string>\n"
"			<false />\n"
"		</array>\n"
"	</array>\n"
"	<key>crop_top</key>\n"
"	<array>\n"
"		<array>\n"
"			<string>autocrop</string>\n"
"			<string>FALSE</string>\n"
"			<false />\n"
"		</array>\n"
"	</array>\n"
"	<key>deinterlace</key>\n"
"	<array>\n"
"		<array>\n"
"			<string>decomb</string>\n"
"			<string>TRUE</string>\n"
"			<true />\n"
"		</array>\n"
"	</array>\n"
"	<key>detelecine</key>\n"
"	<array>\n"
"		<array>\n"
"			<string>variable_frame_rate</string>\n"
"			<string>TRUE</string>\n"
"			<true />\n"
"		</array>\n"
"	</array>\n"
"	<key>end_chapter</key>\n"
"	<array>\n"
"		<array>\n"
"			<string>title</string>\n"
"			<string>none</string>\n"
"			<true />\n"
"		</array>\n"
"	</array>\n"
"	<key>framerate</key>\n"
"	<array>\n"
"		<array>\n"
"			<string>variable_frame_rate</string>\n"
"			<string>TRUE</string>\n"
"			<true />\n"
"		</array>\n"
"	</array>\n"
"	<key>http_optimize_mp4</key>\n"
"	<array>\n"
"		<array>\n"
"			<string>container</string>\n"
"			<string>mp4|m4v</string>\n"
"			<false />\n"
"		</array>\n"
"	</array>\n"
"	<key>ipod_file</key>\n"
"	<array>\n"
"		<array>\n"
"			<string>container</string>\n"
"			<string>mp4|m4v</string>\n"
"			<false />\n"
"		</array>\n"
"		<array>\n"
"			<string>video_codec</string>\n"
"			<string>x264</string>\n"
"			<false />\n"
"		</array>\n"
"	</array>\n"
"	<key>keep_aspect</key>\n"
"	<array>\n"
"		<array>\n"
"			<string>anamorphic</string>\n"
"			<string>FALSE</string>\n"
"			<false />\n"
"		</array>\n"
"	</array>\n"
"	<key>large_mp4</key>\n"
"	<array>\n"
"		<array>\n"
"			<string>container</string>\n"
"			<string>mp4|m4v</string>\n"
"			<false />\n"
"		</array>\n"
"	</array>\n"
"	<key>picture_label</key>\n"
"	<array>\n"
"		<array>\n"
"			<string>title</string>\n"
"			<string>none</string>\n"
"			<true />\n"
"		</array>\n"
"	</array>\n"
"	<key>picture_tab</key>\n"
"	<array>\n"
"		<array>\n"
"			<string>title</string>\n"
"			<string>none</string>\n"
"			<true />\n"
"		</array>\n"
"	</array>\n"
"	<key>preview_button</key>\n"
"	<array>\n"
"		<array>\n"
"			<string>title</string>\n"
"			<string>none</string>\n"
"			<true />\n"
"		</array>\n"
"	</array>\n"
"	<key>preview_frame</key>\n"
"	<array>\n"
"		<array>\n"
"			<string>title</string>\n"
"			<string>none</string>\n"
"			<true />\n"
"		</array>\n"
"	</array>\n"
"	<key>queue_add</key>\n"
"	<array>\n"
"		<array>\n"
"			<string>title</string>\n"
"			<string>none</string>\n"
"			<true />\n"
"		</array>\n"
"	</array>\n"
"	<key>queue_add_menu</key>\n"
"	<array>\n"
"		<array>\n"
"			<string>title</string>\n"
"			<string>none</string>\n"
"			<true />\n"
"		</array>\n"
"	</array>\n"
"	<key>scale_height</key>\n"
"	<array>\n"
"		<array>\n"
"			<string>autoscale</string>\n"
"			<string>FALSE</string>\n"
"			<false />\n"
"		</array>\n"
"		<array>\n"
"			<string>anamorphic</string>\n"
"			<string>FALSE</string>\n"
"			<false />\n"
"		</array>\n"
"		<array>\n"
"			<string>keep_aspect</string>\n"
"			<string>FALSE</string>\n"
"			<false />\n"
"		</array>\n"
"	</array>\n"
"	<key>scale_width</key>\n"
"	<array>\n"
"		<array>\n"
"			<string>autoscale</string>\n"
"			<string>FALSE</string>\n"
"			<false />\n"
"		</array>\n"
"	</array>\n"
"	<key>show_preview_menu</key>\n"
"	<array>\n"
"		<array>\n"
"			<string>title</string>\n"
"			<string>none</string>\n"
"			<true />\n"
"		</array>\n"
"	</array>\n"
"	<key>start_chapter</key>\n"
"	<array>\n"
"		<array>\n"
"			<string>title</string>\n"
"			<string>none</string>\n"
"			<true />\n"
"		</array>\n"
"	</array>\n"
"	<key>title</key>\n"
"	<array>\n"
"		<array>\n"
"			<string>title</string>\n"
"			<string>none</string>\n"
"			<true />\n"
"		</array>\n"
"	</array>\n"
"	<key>turbo</key>\n"
"	<array>\n"
"		<array>\n"
"			<string>vquality_type_constant</string>\n"
"			<string>TRUE</string>\n"
"			<true />\n"
"		</array>\n"
"		<array>\n"
"			<string>two_pass</string>\n"
"			<string>TRUE</string>\n"
"			<false />\n"
"		</array>\n"
"	</array>\n"
"	<key>tweak_deinterlace</key>\n"
"	<array>\n"
"		<array>\n"
"			<string>decomb</string>\n"
"			<string>TRUE</string>\n"
"			<true />\n"
"		</array>\n"
"	</array>\n"
"	<key>two_pass</key>\n"
"	<array>\n"
"		<array>\n"
"			<string>vquality_type_constant</string>\n"
"			<string>TRUE</string>\n"
"			<true />\n"
"		</array>\n"
"	</array>\n"
"	<key>variable_frame_rate</key>\n"
"	<array>\n"
"		<array>\n"
"			<string>container</string>\n"
"			<string>avi</string>\n"
"			<true />\n"
"		</array>\n"
"	</array>\n"
"	<key>video_bitrate</key>\n"
"	<array>\n"
"		<array>\n"
"			<string>vquality_type_bitrate</string>\n"
"			<string>TRUE</string>\n"
"			<false />\n"
"		</array>\n"
"	</array>\n"
"	<key>video_quality</key>\n"
"	<array>\n"
"		<array>\n"
"			<string>vquality_type_constant</string>\n"
"			<string>TRUE</string>\n"
"			<false />\n"
"		</array>\n"
"	</array>\n"
"	<key>video_target_size</key>\n"
"	<array>\n"
"		<array>\n"
"			<string>vquality_type_target</string>\n"
"			<string>TRUE</string>\n"
"			<false />\n"
"		</array>\n"
"	</array>\n"
"	<key>x264_bime</key>\n"
"	<array>\n"
"		<array>\n"
"			<string>x264_bframes</string>\n"
"			<string>0</string>\n"
"			<true />\n"
"		</array>\n"
"	</array>\n"
"	<key>x264_bpyramid</key>\n"
"	<array>\n"
"		<array>\n"
"			<string>x264_bframes</string>\n"
"			<string>&lt;2</string>\n"
"			<true />\n"
"		</array>\n"
"	</array>\n"
"	<key>x264_brdo</key>\n"
"	<array>\n"
"		<array>\n"
"			<string>x264_bframes</string>\n"
"			<string>0</string>\n"
"			<true />\n"
"		</array>\n"
"		<array>\n"
"			<string>x264_subme</string>\n"
"			<string>&lt;6</string>\n"
"			<true />\n"
"		</array>\n"
"	</array>\n"
"	<key>x264_direct</key>\n"
"	<array>\n"
"		<array>\n"
"			<string>x264_bframes</string>\n"
"			<string>0</string>\n"
"			<true />\n"
"		</array>\n"
"		<array>\n"
"			<string>x264_analyse</string>\n"
"			<string>none</string>\n"
"			<true />\n"
"		</array>\n"
"	</array>\n"
"	<key>x264_merange</key>\n"
"	<array>\n"
"		<array>\n"
"			<string>x264_me</string>\n"
"			<string>umh|esa</string>\n"
"			<false />\n"
"		</array>\n"
"	</array>\n"
"	<key>x264_mixed_refs</key>\n"
"	<array>\n"
"		<array>\n"
"			<string>x264_refs</string>\n"
"			<string>&lt;2</string>\n"
"			<true />\n"
"		</array>\n"
"	</array>\n"
"	<key>x264_tab</key>\n"
"	<array>\n"
"		<array>\n"
"			<string>video_codec</string>\n"
"			<string>x264</string>\n"
"			<false />\n"
"		</array>\n"
"	</array>\n"
"	<key>x264_tab_label</key>\n"
"	<array>\n"
"		<array>\n"
"			<string>video_codec</string>\n"
"			<string>x264</string>\n"
"			<false />\n"
"		</array>\n"
"	</array>\n"
"	<key>x264_trellis</key>\n"
"	<array>\n"
"		<array>\n"
"			<string>x264_cabac</string>\n"
"			<string>TRUE</string>\n"
"			<false />\n"
"		</array>\n"
"	</array>\n"
"	<key>x264_weighted_bframes</key>\n"
"	<array>\n"
"		<array>\n"
"			<string>x264_bframes</string>\n"
"			<string>0</string>\n"
"			<true />\n"
"		</array>\n"
"	</array>\n"
"</dict>\n"
"</plist>\n"
