// --------------------------------------------------------------------------------------------------------------------
// <copyright file="hb_subtitle.cs" company="HandBrake Project (http://handbrake.fr)">
//   This file is part of the HandBrake source code - It may be used under the terms of the GNU General Public License.
// </copyright>
// <auto-generated> Disable Stylecop Warnings for this file  </auto-generated>
// --------------------------------------------------------------------------------------------------------------------

namespace HandBrake.ApplicationServices.Interop.HbLib
{
    public enum hb_subtitle_s_subsource
    {
        VOBSUB,

        SRTSUB,

        CC608SUB,

        CC708SUB,

        UTF8SUB,

        TX3GSUB,

        SSASUB,

        PGSSUB
    }
}
