//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// --------------------------------------------------------------------------------------------------
// <auto-generatedInfo>
// 	This code was generated by ResW File Code Generator (http://bit.ly/reswcodegen)
// 	ResW File Code Generator was written by Christian Resma Helle
// 	and is under GNU General Public License version 2 (GPLv2)
// 
// 	This code contains a helper class exposing property representations
// 	of the string resources defined in the specified .ResW file
// 
// 	Generated: 01/10/2018 20:41:28
// </auto-generatedInfo>
// --------------------------------------------------------------------------------------------------
namespace HandBrake.Resources
{
    using Windows.ApplicationModel.Resources;
    
    
    public sealed partial class Resources
    {
        
        private static ResourceLoader resourceLoader;
        
        static Resources()
        {
            string executingAssemblyName;
            executingAssemblyName = Windows.UI.Xaml.Application.Current.GetType().AssemblyQualifiedName;
            string[] executingAssemblySplit;
            executingAssemblySplit = executingAssemblyName.Split(',');
            executingAssemblyName = executingAssemblySplit[1];
            string currentAssemblyName;
            currentAssemblyName = typeof(Resources).AssemblyQualifiedName;
            string[] currentAssemblySplit;
            currentAssemblySplit = currentAssemblyName.Split(',');
            currentAssemblyName = currentAssemblySplit[1];
            if (executingAssemblyName.Equals(currentAssemblyName))
            {
                resourceLoader = ResourceLoader.GetForCurrentView("Resources");
            }
            else
            {
                resourceLoader = ResourceLoader.GetForCurrentView(currentAssemblyName + "/Resources");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "About"
        /// </summary>
        public static string About
        {
            get
            {
                return resourceLoader.GetString("About");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Activity Log"
        /// </summary>
        public static string ActivityLog
        {
            get
            {
                return resourceLoader.GetString("ActivityLog");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Cancel"
        /// </summary>
        public static string Cancel
        {
            get
            {
                return resourceLoader.GetString("Cancel");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Folder
        ///(Batch Scan)"
        /// </summary>
        public static string Folder_BatchScan_NewLine
        {
            get
            {
                return resourceLoader.GetString("Folder_BatchScan_NewLine");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Help"
        /// </summary>
        public static string Help
        {
            get
            {
                return resourceLoader.GetString("Help");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "No"
        /// </summary>
        public static string No
        {
            get
            {
                return resourceLoader.GetString("No");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "OK"
        /// </summary>
        public static string OK
        {
            get
            {
                return resourceLoader.GetString("OK");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "(None)"
        /// </summary>
        public static string Selected_None
        {
            get
            {
                return resourceLoader.GetString("Selected_None");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Select a source to Encode Videos"
        /// </summary>
        public static string SourceSelection_Description
        {
            get
            {
                return resourceLoader.GetString("SourceSelection_Description");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Optical Drive"
        /// </summary>
        public static string SourceSelection_OpenDVDBluray
        {
            get
            {
                return resourceLoader.GetString("SourceSelection_OpenDVDBluray");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Yes"
        /// </summary>
        public static string Yes
        {
            get
            {
                return resourceLoader.GetString("Yes");
            }
        }
    }
}
