const char hb_builtin_presets_json[] =
"{\n"
"    \"PresetBuiltin\": [\n"
"        {\n"
"            \"ChildrenArray\": [\n"
"                {\n"
"                    \"AudioAllowAACPass\": 1, \n"
"                    \"AudioAllowAC3Pass\": 1, \n"
"                    \"AudioAllowDTSHDPass\": 1, \n"
"                    \"AudioAllowDTSPass\": 1, \n"
"                    \"AudioAllowMP3Pass\": 1, \n"
"                    \"AudioEncoderFallback\": \"ac3\", \n"
"                    \"AudioList\": [\n"
"                        {\n"
"                            \"AudioBitrate\": \"160\", \n"
"                            \"AudioEncoder\": \"aac\", \n"
"                            \"AudioMixdown\": \"dpl2\", \n"
"                            \"AudioSamplerate\": \"auto\", \n"
"                            \"AudioTrack\": 1, \n"
"                            \"AudioTrackDRCSlider\": 0.0, \n"
"                            \"AudioTrackGainSlider\": 0.0\n"
"                        }, \n"
"                        {\n"
"                            \"AudioBitrate\": \"160\", \n"
"                            \"AudioEncoder\": \"copy:ac3\", \n"
"                            \"AudioMixdown\": \"none\", \n"
"                            \"AudioSamplerate\": \"auto\", \n"
"                            \"AudioTrack\": 1, \n"
"                            \"AudioTrackDRCSlider\": 0.0, \n"
"                            \"AudioTrackGainSlider\": 0.0\n"
"                        }\n"
"                    ], \n"
"                    \"ChapterMarkers\": 1, \n"
"                    \"Default\": 0, \n"
"                    \"FileFormat\": \"mp4\", \n"
"                    \"Folder\": false, \n"
"                    \"Mp4HttpOptimize\": 0, \n"
"                    \"Mp4iPodCompatible\": 0, \n"
"                    \"PictureAutoCrop\": 1, \n"
"                    \"PictureBottomCrop\": 0, \n"
"                    \"PictureDeblock\": 0, \n"
"                    \"PictureDecomb\": 0, \n"
"                    \"PictureDecombCustom\": \"\", \n"
"                    \"PictureDecombDeinterlace\": 1, \n"
"                    \"PictureDeinterlace\": 0, \n"
"                    \"PictureDeinterlaceCustom\": \"\", \n"
"                    \"PictureDenoiseCustom\": \"\", \n"
"                    \"PictureDenoiseFilter\": \"off\", \n"
"                    \"PictureDetelecine\": 0, \n"
"                    \"PictureDetelecineCustom\": \"\", \n"
"                    \"PictureHeight\": 576, \n"
"                    \"PictureKeepRatio\": 0, \n"
"                    \"PictureLeftCrop\": 0, \n"
"                    \"PictureModulus\": 2, \n"
"                    \"PicturePAR\": \"loose\", \n"
"                    \"PictureRightCrop\": 0, \n"
"                    \"PictureTopCrop\": 0, \n"
"                    \"PictureWidth\": 720, \n"
"                    \"PresetDescription\": \"HandBrake's settings for compatibility with all Apple devices (including the iPod 6G and later). Includes Dolby Digital audio for surround sound.\", \n"
"                    \"PresetName\": \"Universal\", \n"
"                    \"Type\": 0, \n"
"                    \"UsesPictureFilters\": 1, \n"
"                    \"UsesPictureSettings\": 1, \n"
"                    \"VideoAvgBitrate\": \"2500\", \n"
"                    \"VideoEncoder\": \"x264\", \n"
"                    \"VideoFramerate\": \"30\", \n"
"                    \"VideoFramerateMode\": \"pfr\", \n"
"                    \"VideoGrayScale\": 0, \n"
"                    \"VideoLevel\": \"3.0\", \n"
"                    \"VideoOptionExtra\": \"\", \n"
"                    \"VideoPreset\": \"fast\", \n"
"                    \"VideoProfile\": \"baseline\", \n"
"                    \"VideoQualitySlider\": 20.0, \n"
"                    \"VideoQualityType\": 2, \n"
"                    \"VideoTune\": \"\", \n"
"                    \"VideoTurboTwoPass\": 0, \n"
"                    \"VideoTwoPass\": 0, \n"
"                    \"x264Option\": \"\", \n"
"                    \"x264UseAdvancedOptions\": 0\n"
"                }, \n"
"                {\n"
"                    \"AudioAllowAACPass\": 1, \n"
"                    \"AudioAllowAC3Pass\": 1, \n"
"                    \"AudioAllowDTSHDPass\": 1, \n"
"                    \"AudioAllowDTSPass\": 1, \n"
"                    \"AudioAllowMP3Pass\": 1, \n"
"                    \"AudioEncoderFallback\": \"ac3\", \n"
"                    \"AudioList\": [\n"
"                        {\n"
"                            \"AudioBitrate\": \"160\", \n"
"                            \"AudioEncoder\": \"aac\", \n"
"                            \"AudioMixdown\": \"dpl2\", \n"
"                            \"AudioSamplerate\": \"auto\", \n"
"                            \"AudioTrack\": 1, \n"
"                            \"AudioTrackDRCSlider\": 0.0, \n"
"                            \"AudioTrackGainSlider\": 0.0\n"
"                        }\n"
"                    ], \n"
"                    \"ChapterMarkers\": 1, \n"
"                    \"Default\": 0, \n"
"                    \"FileFormat\": \"mp4\", \n"
"                    \"Folder\": false, \n"
"                    \"Mp4HttpOptimize\": 0, \n"
"                    \"Mp4iPodCompatible\": 1, \n"
"                    \"PictureAutoCrop\": 1, \n"
"                    \"PictureBottomCrop\": 0, \n"
"                    \"PictureDeblock\": 0, \n"
"                    \"PictureDecomb\": 0, \n"
"                    \"PictureDecombCustom\": \"\", \n"
"                    \"PictureDecombDeinterlace\": 1, \n"
"                    \"PictureDeinterlace\": 0, \n"
"                    \"PictureDeinterlaceCustom\": \"\", \n"
"                    \"PictureDenoiseCustom\": \"\", \n"
"                    \"PictureDenoiseFilter\": \"off\", \n"
"                    \"PictureDetelecine\": 0, \n"
"                    \"PictureDetelecineCustom\": \"\", \n"
"                    \"PictureHeight\": 240, \n"
"                    \"PictureKeepRatio\": 1, \n"
"                    \"PictureLeftCrop\": 0, \n"
"                    \"PictureModulus\": 2, \n"
"                    \"PicturePAR\": \"off\", \n"
"                    \"PictureRightCrop\": 0, \n"
"                    \"PictureTopCrop\": 0, \n"
"                    \"PictureWidth\": 320, \n"
"                    \"PresetDescription\": \"HandBrake's settings for playback on the iPod with Video (all generations).\", \n"
"                    \"PresetName\": \"iPod\", \n"
"                    \"Type\": 0, \n"
"                    \"UsesPictureFilters\": 1, \n"
"                    \"UsesPictureSettings\": 1, \n"
"                    \"VideoAvgBitrate\": \"2500\", \n"
"                    \"VideoEncoder\": \"x264\", \n"
"                    \"VideoFramerate\": \"30\", \n"
"                    \"VideoFramerateMode\": \"pfr\", \n"
"                    \"VideoGrayScale\": 0, \n"
"                    \"VideoLevel\": \"1.3\", \n"
"                    \"VideoOptionExtra\": \"\", \n"
"                    \"VideoPreset\": \"medium\", \n"
"                    \"VideoProfile\": \"baseline\", \n"
"                    \"VideoQualitySlider\": 22.0, \n"
"                    \"VideoQualityType\": 2, \n"
"                    \"VideoTune\": \"\", \n"
"                    \"VideoTurboTwoPass\": 0, \n"
"                    \"VideoTwoPass\": 0, \n"
"                    \"x264Option\": \"\", \n"
"                    \"x264UseAdvancedOptions\": 0\n"
"                }, \n"
"                {\n"
"                    \"AudioAllowAACPass\": 1, \n"
"                    \"AudioAllowAC3Pass\": 1, \n"
"                    \"AudioAllowDTSHDPass\": 1, \n"
"                    \"AudioAllowDTSPass\": 1, \n"
"                    \"AudioAllowMP3Pass\": 1, \n"
"                    \"AudioEncoderFallback\": \"ac3\", \n"
"                    \"AudioList\": [\n"
"                        {\n"
"                            \"AudioBitrate\": \"160\", \n"
"                            \"AudioEncoder\": \"aac\", \n"
"                            \"AudioMixdown\": \"dpl2\", \n"
"                            \"AudioSamplerate\": \"auto\", \n"
"                            \"AudioTrack\": 1, \n"
"                            \"AudioTrackDRCSlider\": 0.0, \n"
"                            \"AudioTrackGainSlider\": 0.0\n"
"                        }\n"
"                    ], \n"
"                    \"ChapterMarkers\": 1, \n"
"                    \"Default\": 0, \n"
"                    \"FileFormat\": \"mp4\", \n"
"                    \"Folder\": false, \n"
"                    \"Mp4HttpOptimize\": 0, \n"
"                    \"Mp4iPodCompatible\": 0, \n"
"                    \"PictureAutoCrop\": 1, \n"
"                    \"PictureBottomCrop\": 0, \n"
"                    \"PictureDeblock\": 0, \n"
"                    \"PictureDecomb\": 0, \n"
"                    \"PictureDecombCustom\": \"\", \n"
"                    \"PictureDecombDeinterlace\": 1, \n"
"                    \"PictureDeinterlace\": 0, \n"
"                    \"PictureDeinterlaceCustom\": \"\", \n"
"                    \"PictureDenoiseCustom\": \"\", \n"
"                    \"PictureDenoiseFilter\": \"off\", \n"
"                    \"PictureDetelecine\": 0, \n"
"                    \"PictureDetelecineCustom\": \"\", \n"
"                    \"PictureHeight\": 640, \n"
"                    \"PictureKeepRatio\": 0, \n"
"                    \"PictureLeftCrop\": 0, \n"
"                    \"PictureModulus\": 2, \n"
"                    \"PicturePAR\": \"loose\", \n"
"                    \"PictureRightCrop\": 0, \n"
"                    \"PictureTopCrop\": 0, \n"
"                    \"PictureWidth\": 960, \n"
"                    \"PresetDescription\": \"HandBrake's settings for handheld iOS devices (iPhone 4, iPod touch 3G and later).\", \n"
"                    \"PresetName\": \"iPhone & iPod touch\", \n"
"                    \"Type\": 0, \n"
"                    \"UsesPictureFilters\": 1, \n"
"                    \"UsesPictureSettings\": 1, \n"
"                    \"VideoAvgBitrate\": \"2500\", \n"
"                    \"VideoEncoder\": \"x264\", \n"
"                    \"VideoFramerate\": \"30\", \n"
"                    \"VideoFramerateMode\": \"pfr\", \n"
"                    \"VideoGrayScale\": 0, \n"
"                    \"VideoLevel\": \"3.1\", \n"
"                    \"VideoOptionExtra\": \"\", \n"
"                    \"VideoPreset\": \"medium\", \n"
"                    \"VideoProfile\": \"high\", \n"
"                    \"VideoQualitySlider\": 22.0, \n"
"                    \"VideoQualityType\": 2, \n"
"                    \"VideoTune\": \"\", \n"
"                    \"VideoTurboTwoPass\": 0, \n"
"                    \"VideoTwoPass\": 0, \n"
"                    \"x264Option\": \"\", \n"
"                    \"x264UseAdvancedOptions\": 0\n"
"                }, \n"
"                {\n"
"                    \"AudioAllowAACPass\": 1, \n"
"                    \"AudioAllowAC3Pass\": 1, \n"
"                    \"AudioAllowDTSHDPass\": 1, \n"
"                    \"AudioAllowDTSPass\": 1, \n"
"                    \"AudioAllowMP3Pass\": 1, \n"
"                    \"AudioEncoderFallback\": \"ac3\", \n"
"                    \"AudioList\": [\n"
"                        {\n"
"                            \"AudioBitrate\": \"160\", \n"
"                            \"AudioEncoder\": \"aac\", \n"
"                            \"AudioMixdown\": \"dpl2\", \n"
"                            \"AudioSamplerate\": \"auto\", \n"
"                            \"AudioTrack\": 1, \n"
"                            \"AudioTrackDRCSlider\": 0.0, \n"
"                            \"AudioTrackGainSlider\": 0.0\n"
"                        }\n"
"                    ], \n"
"                    \"ChapterMarkers\": 1, \n"
"                    \"Default\": 0, \n"
"                    \"FileFormat\": \"mp4\", \n"
"                    \"Folder\": false, \n"
"                    \"Mp4HttpOptimize\": 0, \n"
"                    \"Mp4iPodCompatible\": 0, \n"
"                    \"PictureAutoCrop\": 1, \n"
"                    \"PictureBottomCrop\": 0, \n"
"                    \"PictureDeblock\": 0, \n"
"                    \"PictureDecomb\": 0, \n"
"                    \"PictureDecombCustom\": \"\", \n"
"                    \"PictureDecombDeinterlace\": 1, \n"
"                    \"PictureDeinterlace\": 0, \n"
"                    \"PictureDeinterlaceCustom\": \"\", \n"
"                    \"PictureDenoiseCustom\": \"\", \n"
"                    \"PictureDenoiseFilter\": \"off\", \n"
"                    \"PictureDetelecine\": 0, \n"
"                    \"PictureDetelecineCustom\": \"\", \n"
"                    \"PictureHeight\": 720, \n"
"                    \"PictureKeepRatio\": 0, \n"
"                    \"PictureLeftCrop\": 0, \n"
"                    \"PictureModulus\": 2, \n"
"                    \"PicturePAR\": \"loose\", \n"
"                    \"PictureRightCrop\": 0, \n"
"                    \"PictureTopCrop\": 0, \n"
"                    \"PictureWidth\": 1280, \n"
"                    \"PresetDescription\": \"HandBrake's settings for playback on the iPad (all generations).\", \n"
"                    \"PresetName\": \"iPad\", \n"
"                    \"Type\": 0, \n"
"                    \"UsesPictureFilters\": 1, \n"
"                    \"UsesPictureSettings\": 1, \n"
"                    \"VideoAvgBitrate\": \"2500\", \n"
"                    \"VideoEncoder\": \"x264\", \n"
"                    \"VideoFramerate\": \"30\", \n"
"                    \"VideoFramerateMode\": \"pfr\", \n"
"                    \"VideoGrayScale\": 0, \n"
"                    \"VideoLevel\": \"3.1\", \n"
"                    \"VideoOptionExtra\": \"\", \n"
"                    \"VideoPreset\": \"medium\", \n"
"                    \"VideoProfile\": \"high\", \n"
"                    \"VideoQualitySlider\": 20.0, \n"
"                    \"VideoQualityType\": 2, \n"
"                    \"VideoTune\": \"\", \n"
"                    \"VideoTurboTwoPass\": 0, \n"
"                    \"VideoTwoPass\": 0, \n"
"                    \"x264Option\": \"\", \n"
"                    \"x264UseAdvancedOptions\": 0\n"
"                }, \n"
"                {\n"
"                    \"AudioAllowAACPass\": 1, \n"
"                    \"AudioAllowAC3Pass\": 1, \n"
"                    \"AudioAllowDTSHDPass\": 1, \n"
"                    \"AudioAllowDTSPass\": 1, \n"
"                    \"AudioAllowMP3Pass\": 1, \n"
"                    \"AudioEncoderFallback\": \"ac3\", \n"
"                    \"AudioList\": [\n"
"                        {\n"
"                            \"AudioBitrate\": \"160\", \n"
"                            \"AudioEncoder\": \"aac\", \n"
"                            \"AudioMixdown\": \"dpl2\", \n"
"                            \"AudioSamplerate\": \"auto\", \n"
"                            \"AudioTrack\": 1, \n"
"                            \"AudioTrackDRCSlider\": 0.0, \n"
"                            \"AudioTrackGainSlider\": 0.0\n"
"                        }, \n"
"                        {\n"
"                            \"AudioBitrate\": \"160\", \n"
"                            \"AudioEncoder\": \"copy:ac3\", \n"
"                            \"AudioMixdown\": \"none\", \n"
"                            \"AudioSamplerate\": \"auto\", \n"
"                            \"AudioTrack\": 1, \n"
"                            \"AudioTrackDRCSlider\": 0.0, \n"
"                            \"AudioTrackGainSlider\": 0.0\n"
"                        }\n"
"                    ], \n"
"                    \"ChapterMarkers\": 1, \n"
"                    \"Default\": 0, \n"
"                    \"FileFormat\": \"mp4\", \n"
"                    \"Folder\": false, \n"
"                    \"Mp4HttpOptimize\": 0, \n"
"                    \"Mp4iPodCompatible\": 0, \n"
"                    \"PictureAutoCrop\": 1, \n"
"                    \"PictureBottomCrop\": 0, \n"
"                    \"PictureDeblock\": 0, \n"
"                    \"PictureDecomb\": 0, \n"
"                    \"PictureDecombCustom\": \"\", \n"
"                    \"PictureDecombDeinterlace\": 1, \n"
"                    \"PictureDeinterlace\": 0, \n"
"                    \"PictureDeinterlaceCustom\": \"\", \n"
"                    \"PictureDenoiseCustom\": \"\", \n"
"                    \"PictureDenoiseFilter\": \"off\", \n"
"                    \"PictureDetelecine\": 0, \n"
"                    \"PictureDetelecineCustom\": \"\", \n"
"                    \"PictureHeight\": 720, \n"
"                    \"PictureKeepRatio\": 0, \n"
"                    \"PictureLeftCrop\": 0, \n"
"                    \"PictureModulus\": 2, \n"
"                    \"PicturePAR\": \"loose\", \n"
"                    \"PictureRightCrop\": 0, \n"
"                    \"PictureTopCrop\": 0, \n"
"                    \"PictureWidth\": 960, \n"
"                    \"PresetDescription\": \"HandBrake's settings for the original AppleTV. Includes Dolby Digital audio for surround sound. Also compatible with iOS devices released since 2009.\", \n"
"                    \"PresetName\": \"AppleTV\", \n"
"                    \"Type\": 0, \n"
"                    \"UsesPictureFilters\": 1, \n"
"                    \"UsesPictureSettings\": 1, \n"
"                    \"VideoAvgBitrate\": \"2500\", \n"
"                    \"VideoEncoder\": \"x264\", \n"
"                    \"VideoFramerate\": \"30\", \n"
"                    \"VideoFramerateMode\": \"pfr\", \n"
"                    \"VideoGrayScale\": 0, \n"
"                    \"VideoLevel\": \"3.1\", \n"
"                    \"VideoOptionExtra\": \"qpmin=4:cabac=0:ref=2:b-pyramid=none:weightb=0:weightp=0:vbv-maxrate=9500:vbv-bufsize=9500\", \n"
"                    \"VideoPreset\": \"medium\", \n"
"                    \"VideoProfile\": \"high\", \n"
"                    \"VideoQualitySlider\": 20.0, \n"
"                    \"VideoQualityType\": 2, \n"
"                    \"VideoTune\": \"\", \n"
"                    \"VideoTurboTwoPass\": 0, \n"
"                    \"VideoTwoPass\": 0, \n"
"                    \"x264Option\": \"\", \n"
"                    \"x264UseAdvancedOptions\": 0\n"
"                }, \n"
"                {\n"
"                    \"AudioAllowAACPass\": 1, \n"
"                    \"AudioAllowAC3Pass\": 1, \n"
"                    \"AudioAllowDTSHDPass\": 1, \n"
"                    \"AudioAllowDTSPass\": 1, \n"
"                    \"AudioAllowMP3Pass\": 1, \n"
"                    \"AudioEncoderFallback\": \"ac3\", \n"
"                    \"AudioList\": [\n"
"                        {\n"
"                            \"AudioBitrate\": \"160\", \n"
"                            \"AudioEncoder\": \"aac\", \n"
"                            \"AudioMixdown\": \"dpl2\", \n"
"                            \"AudioSamplerate\": \"auto\", \n"
"                            \"AudioTrack\": 1, \n"
"                            \"AudioTrackDRCSlider\": 0.0, \n"
"                            \"AudioTrackGainSlider\": 0.0\n"
"                        }, \n"
"                        {\n"
"                            \"AudioBitrate\": \"160\", \n"
"                            \"AudioEncoder\": \"copy:ac3\", \n"
"                            \"AudioMixdown\": \"none\", \n"
"                            \"AudioSamplerate\": \"auto\", \n"
"                            \"AudioTrack\": 1, \n"
"                            \"AudioTrackDRCSlider\": 0.0, \n"
"                            \"AudioTrackGainSlider\": 0.0\n"
"                        }\n"
"                    ], \n"
"                    \"ChapterMarkers\": 1, \n"
"                    \"Default\": 0, \n"
"                    \"FileFormat\": \"mp4\", \n"
"                    \"Folder\": false, \n"
"                    \"Mp4HttpOptimize\": 0, \n"
"                    \"Mp4iPodCompatible\": 0, \n"
"                    \"PictureAutoCrop\": 1, \n"
"                    \"PictureBottomCrop\": 0, \n"
"                    \"PictureDeblock\": 0, \n"
"                    \"PictureDecomb\": 0, \n"
"                    \"PictureDecombCustom\": \"\", \n"
"                    \"PictureDecombDeinterlace\": 1, \n"
"                    \"PictureDeinterlace\": 0, \n"
"                    \"PictureDeinterlaceCustom\": \"\", \n"
"                    \"PictureDenoiseCustom\": \"\", \n"
"                    \"PictureDenoiseFilter\": \"off\", \n"
"                    \"PictureDetelecine\": 0, \n"
"                    \"PictureDetelecineCustom\": \"\", \n"
"                    \"PictureHeight\": 720, \n"
"                    \"PictureKeepRatio\": 0, \n"
"                    \"PictureLeftCrop\": 0, \n"
"                    \"PictureModulus\": 2, \n"
"                    \"PicturePAR\": \"loose\", \n"
"                    \"PictureRightCrop\": 0, \n"
"                    \"PictureTopCrop\": 0, \n"
"                    \"PictureWidth\": 1280, \n"
"                    \"PresetDescription\": \"HandBrake's settings for the second-generation AppleTV. Includes Dolby Digital audio for surround sound. NOT compatible with the original AppleTV.\", \n"
"                    \"PresetName\": \"AppleTV 2\", \n"
"                    \"Type\": 0, \n"
"                    \"UsesPictureFilters\": 1, \n"
"                    \"UsesPictureSettings\": 1, \n"
"                    \"VideoAvgBitrate\": \"2500\", \n"
"                    \"VideoEncoder\": \"x264\", \n"
"                    \"VideoFramerate\": \"30\", \n"
"                    \"VideoFramerateMode\": \"pfr\", \n"
"                    \"VideoGrayScale\": 0, \n"
"                    \"VideoLevel\": \"3.1\", \n"
"                    \"VideoOptionExtra\": \"\", \n"
"                    \"VideoPreset\": \"medium\", \n"
"                    \"VideoProfile\": \"high\", \n"
"                    \"VideoQualitySlider\": 20.0, \n"
"                    \"VideoQualityType\": 2, \n"
"                    \"VideoTune\": \"\", \n"
"                    \"VideoTurboTwoPass\": 0, \n"
"                    \"VideoTwoPass\": 0, \n"
"                    \"x264Option\": \"\", \n"
"                    \"x264UseAdvancedOptions\": 0\n"
"                }, \n"
"                {\n"
"                    \"AudioAllowAACPass\": 1, \n"
"                    \"AudioAllowAC3Pass\": 1, \n"
"                    \"AudioAllowDTSHDPass\": 1, \n"
"                    \"AudioAllowDTSPass\": 1, \n"
"                    \"AudioAllowMP3Pass\": 1, \n"
"                    \"AudioEncoderFallback\": \"ac3\", \n"
"                    \"AudioList\": [\n"
"                        {\n"
"                            \"AudioBitrate\": \"160\", \n"
"                            \"AudioEncoder\": \"aac\", \n"
"                            \"AudioMixdown\": \"dpl2\", \n"
"                            \"AudioSamplerate\": \"auto\", \n"
"                            \"AudioTrack\": 1, \n"
"                            \"AudioTrackDRCSlider\": 0.0, \n"
"                            \"AudioTrackGainSlider\": 0.0\n"
"                        }, \n"
"                        {\n"
"                            \"AudioBitrate\": \"160\", \n"
"                            \"AudioEncoder\": \"copy:ac3\", \n"
"                            \"AudioMixdown\": \"none\", \n"
"                            \"AudioSamplerate\": \"auto\", \n"
"                            \"AudioTrack\": 1, \n"
"                            \"AudioTrackDRCSlider\": 0.0, \n"
"                            \"AudioTrackGainSlider\": 0.0\n"
"                        }\n"
"                    ], \n"
"                    \"ChapterMarkers\": 1, \n"
"                    \"Default\": 0, \n"
"                    \"FileFormat\": \"mp4\", \n"
"                    \"Folder\": false, \n"
"                    \"Mp4HttpOptimize\": 0, \n"
"                    \"Mp4iPodCompatible\": 0, \n"
"                    \"PictureAutoCrop\": 1, \n"
"                    \"PictureBottomCrop\": 0, \n"
"                    \"PictureDeblock\": 0, \n"
"                    \"PictureDecomb\": 3, \n"
"                    \"PictureDecombCustom\": \"\", \n"
"                    \"PictureDecombDeinterlace\": 1, \n"
"                    \"PictureDeinterlace\": 0, \n"
"                    \"PictureDeinterlaceCustom\": \"\", \n"
"                    \"PictureDenoiseCustom\": \"\", \n"
"                    \"PictureDenoiseFilter\": \"off\", \n"
"                    \"PictureDetelecine\": 0, \n"
"                    \"PictureDetelecineCustom\": \"\", \n"
"                    \"PictureHeight\": 1080, \n"
"                    \"PictureKeepRatio\": 0, \n"
"                    \"PictureLeftCrop\": 0, \n"
"                    \"PictureModulus\": 2, \n"
"                    \"PicturePAR\": \"loose\", \n"
"                    \"PictureRightCrop\": 0, \n"
"                    \"PictureTopCrop\": 0, \n"
"                    \"PictureWidth\": 1920, \n"
"                    \"PresetDescription\": \"HandBrake's settings for the third-generation AppleTV. Includes Dolby Digital audio for surround sound. NOT compatible with the original AppleTV. May stutter on the second-generation AppleTV.\", \n"
"                    \"PresetName\": \"AppleTV 3\", \n"
"                    \"Type\": 0, \n"
"                    \"UsesPictureFilters\": 1, \n"
"                    \"UsesPictureSettings\": 1, \n"
"                    \"VideoAvgBitrate\": \"2500\", \n"
"                    \"VideoEncoder\": \"x264\", \n"
"                    \"VideoFramerate\": \"30\", \n"
"                    \"VideoFramerateMode\": \"pfr\", \n"
"                    \"VideoGrayScale\": 0, \n"
"                    \"VideoLevel\": \"4.0\", \n"
"                    \"VideoOptionExtra\": \"\", \n"
"                    \"VideoPreset\": \"medium\", \n"
"                    \"VideoProfile\": \"high\", \n"
"                    \"VideoQualitySlider\": 20.0, \n"
"                    \"VideoQualityType\": 2, \n"
"                    \"VideoTune\": \"\", \n"
"                    \"VideoTurboTwoPass\": 0, \n"
"                    \"VideoTwoPass\": 0, \n"
"                    \"x264Option\": \"\", \n"
"                    \"x264UseAdvancedOptions\": 0\n"
"                }, \n"
"                {\n"
"                    \"AudioAllowAACPass\": 1, \n"
"                    \"AudioAllowAC3Pass\": 1, \n"
"                    \"AudioAllowDTSHDPass\": 1, \n"
"                    \"AudioAllowDTSPass\": 1, \n"
"                    \"AudioAllowMP3Pass\": 1, \n"
"                    \"AudioEncoderFallback\": \"ac3\", \n"
"                    \"AudioList\": [\n"
"                        {\n"
"                            \"AudioBitrate\": \"128\", \n"
"                            \"AudioEncoder\": \"aac\", \n"
"                            \"AudioMixdown\": \"dpl2\", \n"
"                            \"AudioSamplerate\": \"auto\", \n"
"                            \"AudioTrack\": 1, \n"
"                            \"AudioTrackDRCSlider\": 0.0, \n"
"                            \"AudioTrackGainSlider\": 0.0\n"
"                        }\n"
"                    ], \n"
"                    \"ChapterMarkers\": 0, \n"
"                    \"Default\": 0, \n"
"                    \"FileFormat\": \"mp4\", \n"
"                    \"Folder\": false, \n"
"                    \"Mp4HttpOptimize\": 0, \n"
"                    \"Mp4iPodCompatible\": 0, \n"
"                    \"PictureAutoCrop\": 1, \n"
"                    \"PictureBottomCrop\": 0, \n"
"                    \"PictureDeblock\": 0, \n"
"                    \"PictureDecomb\": 0, \n"
"                    \"PictureDecombCustom\": \"\", \n"
"                    \"PictureDecombDeinterlace\": 1, \n"
"                    \"PictureDeinterlace\": 0, \n"
"                    \"PictureDeinterlaceCustom\": \"\", \n"
"                    \"PictureDenoiseCustom\": \"\", \n"
"                    \"PictureDenoiseFilter\": \"off\", \n"
"                    \"PictureDetelecine\": 0, \n"
"                    \"PictureDetelecineCustom\": \"\", \n"
"                    \"PictureHeight\": 576, \n"
"                    \"PictureKeepRatio\": 0, \n"
"                    \"PictureLeftCrop\": 0, \n"
"                    \"PictureModulus\": 2, \n"
"                    \"PicturePAR\": \"loose\", \n"
"                    \"PictureRightCrop\": 0, \n"
"                    \"PictureTopCrop\": 0, \n"
"                    \"PictureWidth\": 720, \n"
"                    \"PresetDescription\": \"HandBrake's settings for midrange devices running Android 2.3 or later.\", \n"
"                    \"PresetName\": \"Android\", \n"
"                    \"Type\": 0, \n"
"                    \"UsesPictureFilters\": 1, \n"
"                    \"UsesPictureSettings\": 1, \n"
"                    \"VideoAvgBitrate\": \"2500\", \n"
"                    \"VideoEncoder\": \"x264\", \n"
"                    \"VideoFramerate\": \"30\", \n"
"                    \"VideoFramerateMode\": \"pfr\", \n"
"                    \"VideoGrayScale\": 0, \n"
"                    \"VideoLevel\": \"3.0\", \n"
"                    \"VideoOptionExtra\": \"\", \n"
"                    \"VideoPreset\": \"medium\", \n"
"                    \"VideoProfile\": \"main\", \n"
"                    \"VideoQualitySlider\": 22.0, \n"
"                    \"VideoQualityType\": 2, \n"
"                    \"VideoTune\": \"\", \n"
"                    \"VideoTurboTwoPass\": 0, \n"
"                    \"VideoTwoPass\": 0, \n"
"                    \"x264Option\": \"\", \n"
"                    \"x264UseAdvancedOptions\": 0\n"
"                }, \n"
"                {\n"
"                    \"AudioAllowAACPass\": 1, \n"
"                    \"AudioAllowAC3Pass\": 1, \n"
"                    \"AudioAllowDTSHDPass\": 1, \n"
"                    \"AudioAllowDTSPass\": 1, \n"
"                    \"AudioAllowMP3Pass\": 1, \n"
"                    \"AudioEncoderFallback\": \"ac3\", \n"
"                    \"AudioList\": [\n"
"                        {\n"
"                            \"AudioBitrate\": \"128\", \n"
"                            \"AudioEncoder\": \"aac\", \n"
"                            \"AudioMixdown\": \"dpl2\", \n"
"                            \"AudioSamplerate\": \"auto\", \n"
"                            \"AudioTrack\": 1, \n"
"                            \"AudioTrackDRCSlider\": 0.0, \n"
"                            \"AudioTrackGainSlider\": 0.0\n"
"                        }\n"
"                    ], \n"
"                    \"ChapterMarkers\": 0, \n"
"                    \"Default\": 0, \n"
"                    \"FileFormat\": \"mp4\", \n"
"                    \"Folder\": false, \n"
"                    \"Mp4HttpOptimize\": 0, \n"
"                    \"Mp4iPodCompatible\": 0, \n"
"                    \"PictureAutoCrop\": 1, \n"
"                    \"PictureBottomCrop\": 0, \n"
"                    \"PictureDeblock\": 0, \n"
"                    \"PictureDecomb\": 0, \n"
"                    \"PictureDecombCustom\": \"\", \n"
"                    \"PictureDecombDeinterlace\": 1, \n"
"                    \"PictureDeinterlace\": 0, \n"
"                    \"PictureDeinterlaceCustom\": \"\", \n"
"                    \"PictureDenoiseCustom\": \"\", \n"
"                    \"PictureDenoiseFilter\": \"off\", \n"
"                    \"PictureDetelecine\": 0, \n"
"                    \"PictureDetelecineCustom\": \"\", \n"
"                    \"PictureHeight\": 720, \n"
"                    \"PictureKeepRatio\": 0, \n"
"                    \"PictureLeftCrop\": 0, \n"
"                    \"PictureModulus\": 2, \n"
"                    \"PicturePAR\": \"loose\", \n"
"                    \"PictureRightCrop\": 0, \n"
"                    \"PictureTopCrop\": 0, \n"
"                    \"PictureWidth\": 1280, \n"
"                    \"PresetDescription\": \"HandBrake's preset for tablets running Android 2.3 or later.\", \n"
"                    \"PresetName\": \"Android Tablet\", \n"
"                    \"Type\": 0, \n"
"                    \"UsesPictureFilters\": 1, \n"
"                    \"UsesPictureSettings\": 1, \n"
"                    \"VideoAvgBitrate\": \"2500\", \n"
"                    \"VideoEncoder\": \"x264\", \n"
"                    \"VideoFramerate\": \"30\", \n"
"                    \"VideoFramerateMode\": \"pfr\", \n"
"                    \"VideoGrayScale\": 0, \n"
"                    \"VideoLevel\": \"3.1\", \n"
"                    \"VideoOptionExtra\": \"\", \n"
"                    \"VideoPreset\": \"medium\", \n"
"                    \"VideoProfile\": \"main\", \n"
"                    \"VideoQualitySlider\": 22.0, \n"
"                    \"VideoQualityType\": 2, \n"
"                    \"VideoTune\": \"\", \n"
"                    \"VideoTurboTwoPass\": 0, \n"
"                    \"VideoTwoPass\": 0, \n"
"                    \"x264Option\": \"\", \n"
"                    \"x264UseAdvancedOptions\": 0\n"
"                }, \n"
"                {\n"
"                    \"AudioAllowAACPass\": 1, \n"
"                    \"AudioAllowAC3Pass\": 1, \n"
"                    \"AudioAllowDTSHDPass\": 1, \n"
"                    \"AudioAllowDTSPass\": 1, \n"
"                    \"AudioAllowMP3Pass\": 1, \n"
"                    \"AudioEncoderFallback\": \"ac3\", \n"
"                    \"AudioList\": [\n"
"                        {\n"
"                            \"AudioBitrate\": \"128\", \n"
"                            \"AudioEncoder\": \"aac\", \n"
"                            \"AudioMixdown\": \"dpl2\", \n"
"                            \"AudioSamplerate\": \"auto\", \n"
"                            \"AudioTrack\": 1, \n"
"                            \"AudioTrackDRCSlider\": 0.0, \n"
"                            \"AudioTrackGainSlider\": 0.0\n"
"                        }\n"
"                    ], \n"
"                    \"ChapterMarkers\": 0, \n"
"                    \"Default\": 0, \n"
"                    \"FileFormat\": \"mp4\", \n"
"                    \"Folder\": false, \n"
"                    \"Mp4HttpOptimize\": 0, \n"
"                    \"Mp4iPodCompatible\": 0, \n"
"                    \"PictureAutoCrop\": 1, \n"
"                    \"PictureBottomCrop\": 0, \n"
"                    \"PictureDeblock\": 0, \n"
"                    \"PictureDecomb\": 0, \n"
"                    \"PictureDecombCustom\": \"\", \n"
"                    \"PictureDecombDeinterlace\": 1, \n"
"                    \"PictureDeinterlace\": 0, \n"
"                    \"PictureDeinterlaceCustom\": \"\", \n"
"                    \"PictureDenoiseCustom\": \"\", \n"
"                    \"PictureDenoiseFilter\": \"off\", \n"
"                    \"PictureDetelecine\": 0, \n"
"                    \"PictureDetelecineCustom\": \"\", \n"
"                    \"PictureHeight\": 720, \n"
"                    \"PictureKeepRatio\": 1, \n"
"                    \"PictureLeftCrop\": 0, \n"
"                    \"PictureModulus\": 2, \n"
"                    \"PicturePAR\": \"off\", \n"
"                    \"PictureRightCrop\": 0, \n"
"                    \"PictureTopCrop\": 0, \n"
"                    \"PictureWidth\": 1280, \n"
"                    \"PresetDescription\": \"HandBrake's preset for Windows Phone 8 devices\", \n"
"                    \"PresetName\": \"Windows Phone 8\", \n"
"                    \"Type\": 0, \n"
"                    \"UsesPictureFilters\": 1, \n"
"                    \"UsesPictureSettings\": 1, \n"
"                    \"VideoAvgBitrate\": \"2500\", \n"
"                    \"VideoEncoder\": \"x264\", \n"
"                    \"VideoFramerate\": \"30\", \n"
"                    \"VideoFramerateMode\": \"pfr\", \n"
"                    \"VideoGrayScale\": 0, \n"
"                    \"VideoLevel\": \"3.1\", \n"
"                    \"VideoOptionExtra\": \"\", \n"
"                    \"VideoPreset\": \"medium\", \n"
"                    \"VideoProfile\": \"main\", \n"
"                    \"VideoQualitySlider\": 22.0, \n"
"                    \"VideoQualityType\": 2, \n"
"                    \"VideoTune\": \"\", \n"
"                    \"VideoTurboTwoPass\": 0, \n"
"                    \"VideoTwoPass\": 0, \n"
"                    \"x264Option\": \"\", \n"
"                    \"x264UseAdvancedOptions\": 0\n"
"                }\n"
"            ], \n"
"            \"Default\": 0, \n"
"            \"Folder\": true, \n"
"            \"PresetName\": \"Devices\", \n"
"            \"Type\": 0\n"
"        }, \n"
"        {\n"
"            \"ChildrenArray\": [\n"
"                {\n"
"                    \"AudioAllowAACPass\": 1, \n"
"                    \"AudioAllowAC3Pass\": 1, \n"
"                    \"AudioAllowDTSHDPass\": 1, \n"
"                    \"AudioAllowDTSPass\": 1, \n"
"                    \"AudioAllowMP3Pass\": 1, \n"
"                    \"AudioEncoderFallback\": \"ac3\", \n"
"                    \"AudioList\": [\n"
"                        {\n"
"                            \"AudioBitrate\": \"160\", \n"
"                            \"AudioEncoder\": \"aac\", \n"
"                            \"AudioMixdown\": \"dpl2\", \n"
"                            \"AudioSamplerate\": \"auto\", \n"
"                            \"AudioTrack\": 1, \n"
"                            \"AudioTrackDRCSlider\": 0.0, \n"
"                            \"AudioTrackGainSlider\": 0.0\n"
"                        }\n"
"                    ], \n"
"                    \"ChapterMarkers\": 1, \n"
"                    \"Default\": 1, \n"
"                    \"FileFormat\": \"mp4\", \n"
"                    \"Folder\": false, \n"
"                    \"Mp4HttpOptimize\": 0, \n"
"                    \"Mp4iPodCompatible\": 0, \n"
"                    \"PictureAutoCrop\": 1, \n"
"                    \"PictureBottomCrop\": 0, \n"
"                    \"PictureDeblock\": 0, \n"
"                    \"PictureDecomb\": 0, \n"
"                    \"PictureDecombCustom\": \"\", \n"
"                    \"PictureDecombDeinterlace\": 1, \n"
"                    \"PictureDeinterlace\": 0, \n"
"                    \"PictureDeinterlaceCustom\": \"\", \n"
"                    \"PictureDenoiseCustom\": \"\", \n"
"                    \"PictureDenoiseFilter\": \"off\", \n"
"                    \"PictureDetelecine\": 0, \n"
"                    \"PictureDetelecineCustom\": \"\", \n"
"                    \"PictureHeight\": 0, \n"
"                    \"PictureKeepRatio\": 0, \n"
"                    \"PictureLeftCrop\": 0, \n"
"                    \"PictureModulus\": 2, \n"
"                    \"PicturePAR\": \"loose\", \n"
"                    \"PictureRightCrop\": 0, \n"
"                    \"PictureTopCrop\": 0, \n"
"                    \"PictureWidth\": 0, \n"
"                    \"PresetDescription\": \"HandBrake's normal, default settings.\", \n"
"                    \"PresetName\": \"Normal\", \n"
"                    \"Type\": 0, \n"
"                    \"UsesPictureFilters\": 1, \n"
"                    \"UsesPictureSettings\": 1, \n"
"                    \"VideoAvgBitrate\": \"2500\", \n"
"                    \"VideoEncoder\": \"x264\", \n"
"                    \"VideoFramerate\": \"auto\", \n"
"                    \"VideoFramerateMode\": \"vfr\", \n"
"                    \"VideoGrayScale\": 0, \n"
"                    \"VideoLevel\": \"4.0\", \n"
"                    \"VideoOptionExtra\": \"\", \n"
"                    \"VideoPreset\": \"veryfast\", \n"
"                    \"VideoProfile\": \"main\", \n"
"                    \"VideoQualitySlider\": 20.0, \n"
"                    \"VideoQualityType\": 2, \n"
"                    \"VideoTune\": \"\", \n"
"                    \"VideoTurboTwoPass\": 0, \n"
"                    \"VideoTwoPass\": 0, \n"
"                    \"x264Option\": \"\", \n"
"                    \"x264UseAdvancedOptions\": 0\n"
"                }, \n"
"                {\n"
"                    \"AudioAllowAACPass\": 1, \n"
"                    \"AudioAllowAC3Pass\": 1, \n"
"                    \"AudioAllowDTSHDPass\": 1, \n"
"                    \"AudioAllowDTSPass\": 1, \n"
"                    \"AudioAllowMP3Pass\": 1, \n"
"                    \"AudioEncoderFallback\": \"ac3\", \n"
"                    \"AudioList\": [\n"
"                        {\n"
"                            \"AudioBitrate\": \"160\", \n"
"                            \"AudioEncoder\": \"aac\", \n"
"                            \"AudioMixdown\": \"dpl2\", \n"
"                            \"AudioSamplerate\": \"auto\", \n"
"                            \"AudioTrack\": 1, \n"
"                            \"AudioTrackDRCSlider\": 0.0, \n"
"                            \"AudioTrackGainSlider\": 0.0\n"
"                        }, \n"
"                        {\n"
"                            \"AudioBitrate\": \"160\", \n"
"                            \"AudioEncoder\": \"copy:ac3\", \n"
"                            \"AudioMixdown\": \"none\", \n"
"                            \"AudioSamplerate\": \"auto\", \n"
"                            \"AudioTrack\": 1, \n"
"                            \"AudioTrackDRCSlider\": 0.0, \n"
"                            \"AudioTrackGainSlider\": 0.0\n"
"                        }\n"
"                    ], \n"
"                    \"ChapterMarkers\": 1, \n"
"                    \"Default\": 0, \n"
"                    \"FileFormat\": \"mp4\", \n"
"                    \"Folder\": false, \n"
"                    \"Mp4HttpOptimize\": 0, \n"
"                    \"Mp4iPodCompatible\": 0, \n"
"                    \"PictureAutoCrop\": 1, \n"
"                    \"PictureBottomCrop\": 0, \n"
"                    \"PictureDeblock\": 0, \n"
"                    \"PictureDecomb\": 2, \n"
"                    \"PictureDecombCustom\": \"\", \n"
"                    \"PictureDecombDeinterlace\": 1, \n"
"                    \"PictureDeinterlace\": 0, \n"
"                    \"PictureDeinterlaceCustom\": \"\", \n"
"                    \"PictureDenoiseCustom\": \"\", \n"
"                    \"PictureDenoiseFilter\": \"off\", \n"
"                    \"PictureDetelecine\": 0, \n"
"                    \"PictureDetelecineCustom\": \"\", \n"
"                    \"PictureHeight\": 0, \n"
"                    \"PictureKeepRatio\": 0, \n"
"                    \"PictureLeftCrop\": 0, \n"
"                    \"PictureModulus\": 2, \n"
"                    \"PicturePAR\": \"loose\", \n"
"                    \"PictureRightCrop\": 0, \n"
"                    \"PictureTopCrop\": 0, \n"
"                    \"PictureWidth\": 0, \n"
"                    \"PresetDescription\": \"HandBrake's general-purpose preset for High Profile H.264 video.\", \n"
"                    \"PresetName\": \"High Profile\", \n"
"                    \"Type\": 0, \n"
"                    \"UsesPictureFilters\": 1, \n"
"                    \"UsesPictureSettings\": 1, \n"
"                    \"VideoAvgBitrate\": \"2500\", \n"
"                    \"VideoEncoder\": \"x264\", \n"
"                    \"VideoFramerate\": \"auto\", \n"
"                    \"VideoFramerateMode\": \"vfr\", \n"
"                    \"VideoGrayScale\": 0, \n"
"                    \"VideoLevel\": \"4.1\", \n"
"                    \"VideoOptionExtra\": \"\", \n"
"                    \"VideoPreset\": \"medium\", \n"
"                    \"VideoProfile\": \"high\", \n"
"                    \"VideoQualitySlider\": 20.0, \n"
"                    \"VideoQualityType\": 2, \n"
"                    \"VideoTune\": \"\", \n"
"                    \"VideoTurboTwoPass\": 0, \n"
"                    \"VideoTwoPass\": 0, \n"
"                    \"x264Option\": \"\", \n"
"                    \"x264UseAdvancedOptions\": 0\n"
"                }\n"
"            ], \n"
"            \"Default\": 0, \n"
"            \"Folder\": true, \n"
"            \"PresetName\": \"Regular\", \n"
"            \"Type\": 0\n"
"        }\n"
"    ], \n"
"    \"PresetTemplate\": {\n"
"        \"Preset\": {\n"
"            \"AudioAllowAACPass\": false, \n"
"            \"AudioAllowAC3Pass\": true, \n"
"            \"AudioAllowDTSHDPass\": false, \n"
"            \"AudioAllowDTSPass\": false, \n"
"            \"AudioAllowEAC3Pass\": false, \n"
"            \"AudioAllowFLACPass\": false, \n"
"            \"AudioAllowMP3Pass\": false, \n"
"            \"AudioAllowTRUEHDPass\": false, \n"
"            \"AudioCopyMask\": [], \n"
"            \"AudioEncoderFallback\": \"ac3\", \n"
"            \"AudioLanguageList\": [\n"
"                \"und\"\n"
"            ], \n"
"            \"AudioList\": [\n"
"                {\n"
"                    \"AudioBitrate\": \"192\", \n"
"                    \"AudioCompressionLevel\": -1.0, \n"
"                    \"AudioDitherMethod\": \"auto\", \n"
"                    \"AudioEncoder\": \"copy:ac3\", \n"
"                    \"AudioMixdown\": \"dpl2\", \n"
"                    \"AudioNormalizeMixLevel\": false, \n"
"                    \"AudioSamplerate\": \"auto\", \n"
"                    \"AudioTrackDRCSlider\": 0.0, \n"
"                    \"AudioTrackGainSlider\": 0.0, \n"
"                    \"AudioTrackQuality\": -1.0, \n"
"                    \"AudioTrackQualityEnable\": false\n"
"                }\n"
"            ], \n"
"            \"AudioSecondaryEncoderMode\": true, \n"
"            \"AudioTrackSelectionBehavior\": \"first\", \n"
"            \"ChapterMarkers\": true, \n"
"            \"Default\": false, \n"
"            \"FileFormat\": \"mp4\", \n"
"            \"Folder\": false, \n"
"            \"Mp4HttpOptimize\": false, \n"
"            \"Mp4iPodCompatible\": false, \n"
"            \"PictureAutoCrop\": true, \n"
"            \"PictureBottomCrop\": 0, \n"
"            \"PictureDARWidth\": 0, \n"
"            \"PictureDeblock\": 0, \n"
"            \"PictureDecomb\": \"off\", \n"
"            \"PictureDecombCustom\": \"\", \n"
"            \"PictureDecombDeinterlace\": true, \n"
"            \"PictureDeinterlace\": \"off\", \n"
"            \"PictureDeinterlaceCustom\": \"\", \n"
"            \"PictureDenoiseCustom\": \"\", \n"
"            \"PictureDenoiseFilter\": \"off\", \n"
"            \"PictureDenoisePreset\": \"medium\", \n"
"            \"PictureDenoiseTune\": \"none\", \n"
"            \"PictureDetelecine\": \"off\", \n"
"            \"PictureDetelecineCustom\": \"\", \n"
"            \"PictureForceHeight\": 0, \n"
"            \"PictureForceWidth\": 0, \n"
"            \"PictureHeight\": 0, \n"
"            \"PictureItuPAR\": false, \n"
"            \"PictureKeepRatio\": true, \n"
"            \"PictureLeftCrop\": 0, \n"
"            \"PictureLooseCrop\": false, \n"
"            \"PictureModulus\": 2, \n"
"            \"PicturePAR\": \"loose\", \n"
"            \"PicturePARHeight\": 720, \n"
"            \"PicturePARWidth\": 853, \n"
"            \"PictureRightCrop\": 0, \n"
"            \"PictureRotate\": 0, \n"
"            \"PictureTopCrop\": 0, \n"
"            \"PictureWidth\": 0, \n"
"            \"PresetDescription\": \"\", \n"
"            \"PresetName\": \"Name Missing\", \n"
"            \"SubtitleAddCC\": false, \n"
"            \"SubtitleAddForeignAudioSearch\": false, \n"
"            \"SubtitleAddForeignAudioSubtitle\": false, \n"
"            \"SubtitleBurnBDSub\": false, \n"
"            \"SubtitleBurnBehavior\": \"none\", \n"
"            \"SubtitleBurnDVDSub\": false, \n"
"            \"SubtitleLanguageList\": [], \n"
"            \"SubtitleTrackSelectionBehavior\": \"none\", \n"
"            \"Type\": 1, \n"
"            \"UsesPictureFilters\": true, \n"
"            \"UsesPictureSettings\": 2, \n"
"            \"VideoAvgBitrate\": 1800, \n"
"            \"VideoColorMatrixCode\": 0, \n"
"            \"VideoEncoder\": \"x264\", \n"
"            \"VideoFramerate\": \"auto\", \n"
"            \"VideoFramerateMode\": \"vfr\", \n"
"            \"VideoGrayScale\": false, \n"
"            \"VideoHWDecode\": false, \n"
"            \"VideoLevel\": \"auto\", \n"
"            \"VideoOptionExtra\": \"\", \n"
"            \"VideoPreset\": \"medium\", \n"
"            \"VideoProfile\": \"auto\", \n"
"            \"VideoQSVAsyncDepth\": 4, \n"
"            \"VideoQSVDecode\": false, \n"
"            \"VideoQualitySlider\": 20.0, \n"
"            \"VideoQualityType\": 2, \n"
"            \"VideoScaler\": \"swscale\", \n"
"            \"VideoTune\": \"none\", \n"
"            \"VideoTurboTwoPass\": false, \n"
"            \"VideoTwoPass\": false, \n"
"            \"x264Option\": \"\", \n"
"            \"x264UseAdvancedOptions\": false\n"
"        }, \n"
"        \"VersionMajor\": 10, \n"
"        \"VersionMicro\": 0, \n"
"        \"VersionMinor\": 0\n"
"    }\n"
"}\n";
