name: "Push Notification"
on:
  push:
  pull_request:
      types: [opened, review_requested]

jobs:
  Send_IRC_Notification:
    runs-on: ubuntu-latest
    steps:
      - name: Handle Commit
        uses: rectalogic/notify-irc@v2
        if: github.event_name == 'push' && github.repository == 'HandBrake/HandBrake'
        with:
          channel: "#handbrake"
          nickname: handbrake-bot
          server: irc.libera.chat
          sasl_password: ${{ secrets.LIBERACHAT_PWD }}
          port: 6697
          tls: true
          message: |
            COMMIT: ${{ github.actor }} pushed ${{ github.event.ref }} ${{ github.event.compare }} ${{ join(github.event.commits.*.message) }}
